-- Create study_guides table
CREATE TABLE IF NOT EXISTS study_guides (
  id SERIAL PRIMARY KEY,
  episode_id INTEGER REFERENCES episodes(episode_number),
  title VARCHAR(500) NOT NULL,
  short_answer_questions JSONB NOT NULL,
  essay_questions JSONB NOT NULL,
  glossary JSONB NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_study_guides_episode ON study_guides(episode_id);

-- Insert Episode 1 study guide
INSERT INTO study_guides (episode_id, title, short_answer_questions, essay_questions, glossary)
VALUES (
  1,
  'Comprehensive Study Guide for Test Preparation and Strategy',
  '[
    {"question": "What are the three core components of the \"Plan Big, Study Small\" strategy?", "answer": "The three core components are Information Organization, Time Management, and Study Environment. Information Organization involves creating a complete list of concepts to study, Time Management is about spreading those concepts out over time, and Study Environment focuses on choosing a distraction-free location to maximize focus."},
    {"question": "Explain the concept of \"Modality\" in the context of studying and provide two examples from the text.", "answer": "Modality refers to the method of studying that best aligns with an individual''s learning style. The goal is to make studying more effective by choosing a method that works for you. Examples include visualizing a concept by drawing a diagram, color-coding notes, or using flashcards with keywords or phrases."},
    {"question": "When reviewing a practice test, what three specific groups of questions require special attention?", "answer": "When reviewing a practice test, special attention should be paid to three groups of questions: the questions you got wrong, the questions you got right even if you guessed, and the questions you found difficult or slow to work through. Analyzing these reveals weak areas and where to devote more study time."},
    {"question": "Describe the three recommended phases of the Practice Test Strategy for preparing for an exam.", "answer": "The recommended strategy involves three phases. First is Untimed and Open-Book Practice to focus on applying strategies with notes handy. Second is Timed and Open-Book Practice to work on pacing. The final phase is Timed and Closed-Book Practice to simulate the actual test day conditions as closely as possible."},
    {"question": "What is the primary danger of taking extra time on one difficult question, according to the \"Pace Yourself\" strategy?", "answer": "Taking extra time on one question you don''t understand may keep you from answering two or three other questions that you do know later in the test. The goal is to maximize the number of questions answered correctly, so it is better to make an educated guess on a difficult one and move on."},
    {"question": "According to the text, when is the correct time to initiate the guessing process for a difficult question?", "answer": "The guessing process should begin as soon as you decide that you cannot answer a question based on your existing knowledge. It is a misuse of time to stare at a question for too long, so after a few seconds of realizing you don''t know the answer, it is time to start the process of strategic guessing."},
    {"question": "Explain the \"$5 challenge\" and its purpose in the process of eliminating answer choices.", "answer": "The \"$5 challenge\" is a thought exercise used to prevent the accidental elimination of a correct answer. You should only eliminate an answer choice if you are confident enough that you would be willing to bet $5 that it is wrong, encouraging more careful and less impulsive decisions."},
    {"question": "Define \"Switchback words\" and explain their significance when reading test questions and answers.", "answer": "Switchback words are terms and phrases like \"but,\" \"however,\" and \"despite\" that signal a shift in thought within a sentence. They are significant because they can change the direction of a question or an answer choice, and being aware of them is important for understanding the true meaning."},
    {"question": "What is an \"Answer Choice Family,\" and what does its presence often indicate?", "answer": "An \"Answer Choice Family\" consists of two (or sometimes more) answer choices that are very similar, often presenting as direct opposites or parallels. When you see an answer choice family, it often indicates that the correct answer is more likely to be one of the choices within that family."},
    {"question": "Describe what a \"Fact Trap\" is in the context of answer choice strategies.", "answer": "A \"Fact Trap\" is an answer choice that is a factually true statement on its own but does not correctly answer the specific question being asked. Test-takers must stay focused on the question to avoid being distracted by these seemingly correct, but ultimately irrelevant, options."}
  ]'::jsonb,
  '[
    {"question": "Synthesize the advice from \"Secret #1: Plan Big, Study Small\" and \"Secret #2: Make Your Studying Count.\" How do the principles of information organization, time management, retention, and modality work together to create an effective and efficient study plan?", "guidance": "Formulate comprehensive answers by synthesizing information from across the provided source material."},
    {"question": "Discuss the role of practice tests as described in \"Secret #3: Practice the Right Way\" and \"Week 5: Practice Tests.\" Explain how a strategic approach to practice, including analyzing mistakes and simulating test conditions, can lead to improved performance and confidence.", "guidance": "Formulate comprehensive answers by synthesizing information from across the provided source material."},
    {"question": "Elaborate on the psychological aspects of test-taking as addressed in \"Secret #4: Pace Yourself\" and the \"General Strategies\" section (e.g., Don''t Rush, Keep Moving). How can managing time, anxiety, and momentum during the test impact the final score?", "guidance": "Formulate comprehensive answers by synthesizing information from across the provided source material."},
    {"question": "Analyze the complete \"Plan for Guessing\" outlined in Secret #5. Detail the process from deciding when to guess, to the statistical and psychological methods for narrowing choices (including the probability chart and the $5 challenge), and finally, the strategy for selecting from the remaining options.", "guidance": "Formulate comprehensive answers by synthesizing information from across the provided source material."},
    {"question": "Compare and contrast the \"Question Strategies\" (e.g., Contextual Clues, Hedge Words) with the \"Answer Choice Strategies\" (e.g., Avoid Fact Traps, Benchmark). How do these two sets of tactics complement each other to maximize the chances of selecting the correct answer?", "guidance": "Formulate comprehensive answers by synthesizing information from across the provided source material."}
  ]'::jsonb,
  '[
    {"term": "$5 challenge", "definition": "A thought exercise where a test-taker only eliminates an answer choice if they are confident enough to bet $5 on it being wrong, designed to prevent the accidental elimination of the correct answer."},
    {"term": "Answer Choice Families", "definition": "Two or more answer choices that are very similar, often direct opposites or parallels. The correct answer is frequently found within such a family."},
    {"term": "Benchmark", "definition": "An answer choice that appears to answer the question well and can be used as a standard against which to compare the other, potentially weaker, choices."},
    {"term": "Contextual Clues", "definition": "Information from the context of a question that can help a test-taker decipher the meaning of an unfamiliar word or concept."},
    {"term": "Extreme Statements", "definition": "Answer choices that propose absolute truths or extreme actions. These are often incorrect as they leave no room for exceptions and are difficult to defend."},
    {"term": "Fact Traps", "definition": "Answer choices that are factually true statements but do not actually answer the specific question being asked."},
    {"term": "Hedge Words", "definition": "Words such as may, can, often, usually, generally, and rarely that qualify a statement, making it less absolute. Correct answers often contain hedge words."},
    {"term": "Information Organization", "definition": "The initial step of a study plan, which involves creating a comprehensive list of all concepts that need to be covered and organizing them into manageable groups."},
    {"term": "Modality", "definition": "The method or means by which one studies. This should be chosen to align with an individual''s personal learning style to maximize effectiveness."},
    {"term": "Prefixes", "definition": "A part of a word that comes before the root word. Dissecting prefixes can offer clues to the meaning of an unfamiliar term."},
    {"term": "Practice Test Strategy", "definition": "A recommended three-phase approach to practice exams: (1) Untimed and Open-Book, (2) Timed and Open-Book, and (3) Timed and Closed-Book, to build skills and simulate test conditions."},
    {"term": "Retention", "definition": "The ability to remember and recall material that has been studied. Techniques to improve retention include putting concepts into practice and explaining them to others."},
    {"term": "Study Environment", "definition": "The physical location where studying occurs. An effective study environment is distraction-free to promote focus and make study time more productive."},
    {"term": "Switchback Words", "definition": "Words and phrases such as but, however, despite, and on the other hand that signal a shift in thought or a change in the direction of a question or answer choice."},
    {"term": "Time Management", "definition": "A study technique that involves spreading learning out over the available time, focusing on small amounts daily, and scheduling study sessions to avoid last-minute cramming."}
  ]'::jsonb
)
ON CONFLICT DO NOTHING;

-- Insert Episode 3 study guide
INSERT INTO study_guides (episode_id, title, short_answer_questions, essay_questions, glossary)
VALUES (
  3,
  'Safety and Infection Control Study Guide',
  '[
    {"question": "What are the general goals outlined by The Joint Commission for improving patient safety in a healthcare facility?", "answer": "The Joint Commission''s patient safety goals include using a two-way system to identify patients, ensuring careful written communication about patient care, preventing infections, and having a fall prevention program. The overall aim is to create systems that help avoid errors of identification and miscommunication. Patients are also encouraged to be active participants in their own care to help prevent mistakes."},
    {"question": "Explain the R.A.C.E. acronym and its role in responding to a fire within a hospital.", "answer": "The R.A.C.E. acronym is a protocol for fire safety in a hospital. \"R\" stands for rescuing all patients from the immediate area of danger. \"A\" is for activating the alarm by pulling the fire alarm and calling 9-1-1. \"C\" means to contain the fire by closing all doors, and \"E\" stands for evacuate/extinguish, using a fire extinguisher if appropriate."},
    {"question": "Describe the primary differences between a multiple-casualty incident and a mass-casualty incident.", "answer": "A multiple-casualty incident involves more than one person, typically at least three patients, and requires a response from one to three agencies. A mass-casualty incident also involves more than one person but can involve much larger numbers—dozens, hundreds, or even thousands—and requires multiple jurisdictions and agencies to respond."},
    {"question": "What is the immediate protocol a healthcare provider should follow after sustaining a needlestick injury?", "answer": "Immediately after a needlestick injury, the provider should irrigate the puncture with soap and water. The incident must be reported to a supervisor as soon as possible, and the source patient''s health history should be reviewed. The provider should be offered post-exposure prophylaxis (PEP) for HIV, Hepatitis B, and Hepatitis C if necessary."},
    {"question": "What is the primary purpose of an infection control surveillance plan and what are its key objectives?", "answer": "The primary purpose of an infection control surveillance plan is to identify a means to decrease the rates of hospital-acquired infections. Its key objectives include evaluating the effectiveness of control measures (like handwashing), establishing threshold rates to trigger action, identifying outbreaks, assessing staff compliance, and meeting accreditation standards."},
    {"question": "List the essential safety precautions that must be implemented for a patient undergoing internal radiation therapy (brachytherapy).", "answer": "For patients receiving brachytherapy, safeguards include specific limitations and requirements posted at the room''s entrance, such as time limits for contact. Visitors should stay at least 6 feet from the patient and remain no longer than 30 minutes daily. Staff must be limited to those who are not pregnant, wear dosimeters for contact, and only enter the room when necessary to provide care according to posted guidelines."},
    {"question": "What are the three main principles of ergonomics that a nurse should follow to prevent workplace injury and stress?", "answer": "The three main principles of ergonomics are body mechanics, lifting, and repetition. Proper body mechanics involves keeping the body aligned with a wide base of support and using larger muscles. Proper lifting technique includes using transfer devices, keeping weights close to the body, and never bending or twisting. Finally, nurses should avoid repetitive movements and use proper safety equipment when necessary."},
    {"question": "Describe the four color-coded categories used in primary triage during mass casualty events.", "answer": "The four primary triage categories are: P1-Red (immediate care for systemic life-threatening conditions), P2-Yellow (delayed care for patients who are stable but need medical attention), P3-Green (minor injuries where patients can wait hours for treatment), and P4-Black (deceased or with injuries so extensive they are not survivable)."},
    {"question": "According to the source text, what specific actions should be taken to prevent errors from verbal or handwritten medication orders?", "answer": "To prevent errors, The Joint Commission has established a list of abbreviations to avoid. For handwritten orders, they should be block printed to reduce the chance of illegible writing. Verbal orders should be repeated back to the physician for verification, and facilities should have an institutional policy for the administration of medications to educate staff."},
    {"question": "What does the B-NICE acronym represent in the context of terrorist attacks, and what is its purpose?", "answer": "The B-NICE acronym identifies the categories of hazardous agents associated with terrorist attacks: Biological, Nuclear/Radiological, Incendiary, Chemical, and Explosives. Its purpose is to provide a framework for the types of responses and personal protective equipment (PPE) required for each type of agent during an emergency."}
  ]'::jsonb,
  '[
    {"question": "Describe the process of developing a comprehensive Disaster Management Plan for a healthcare facility. Your answer should detail the initial planning steps, list and explain at least five different types of specific disaster plans that could be included, and outline the two distinct periods of the disaster recovery aspect.", "guidance": "Formulate comprehensive essay response, synthesizing information from across the provided source materials."},
    {"question": "Discuss the multifaceted approach to ensuring patient safety and preventing injury within a hospital setting as outlined in the text. Cover at least four distinct areas, such as the Joint Commission''s goals, protocols for specific patient deficits (e.g., visual, hearing), seizure precautions, and physical environmental controls (e.g., room assignments, electrical safety).", "guidance": "Formulate comprehensive essay response, synthesizing information from across the provided source materials."},
    {"question": "Explain the \"All-Hazards Safety Approach\" to managing mass-casualty incidents. Incorporate the roles of the Incident Command System (ICS), the principles of primary triage, and the specific challenges and organizational plans related to bioterrorism response.", "guidance": "Formulate comprehensive essay response, synthesizing information from across the provided source materials."},
    {"question": "Outline a comprehensive infection control strategy for a hospital. Discuss the difference between common nosocomial infections and catheter-related infections, and detail the various infection control measures, from standard precautions to specific protocols for airborne, droplet, and contact precautions.", "guidance": "Formulate comprehensive essay response, synthesizing information from across the provided source materials."},
    {"question": "Detail the procedures and protocols for handling various hazards within a healthcare facility. Your response should include the safe handling of hazardous materials (including the role of Safety Data Sheets), the proper management of biological/biohazardous waste, the cleaning of small blood spills, and the specific safeguards required for internal radiation therapy.", "guidance": "Formulate comprehensive essay response, synthesizing information from across the provided source materials."}
  ]'::jsonb,
  '[
    {"term": "All-Hazards Safety Approach", "definition": "An emergency management plan that is flexible enough to deal with both natural and man-made disasters, integrating mitigation, preparedness, response, and recovery."},
    {"term": "B-NICE", "definition": "An acronym for hazardous materials associated with terrorist attacks: Biological, Nuclear/Radiological, Incendiary, Chemical, and Explosives."},
    {"term": "Biological/Biohazardous Waste", "definition": "Biological agents or items contaminated with pathogens (human, plant, animal) or infectious agents. This includes blood, cell cultures, and contaminated sharps."},
    {"term": "Bioterrorism", "definition": "The use of biological toxins or infectious agents with the intent to kill or incapacitate humans, animals, or plants as an act of terrorism."},
    {"term": "Brachytherapy", "definition": "A form of internal radiation therapy used to treat a variety of cancers, where radioactive isotopes are administered via IV, intracavitary, per catheters, or interstitial routes."},
    {"term": "Catheter-Related Infections", "definition": "Infections that are a significant cause of morbidity and mortality in the hospital, typically caused by staphylococcus or fungal pathogens that enter the body at the catheter site and can lead to bacteremia."},
    {"term": "Disaster", "definition": "An event where many people are exposed to hazards that result in injury, death, and damage to property. Disasters can be natural (e.g., floods, hurricanes) or caused by human conflict (e.g., riots, bombings)."},
    {"term": "Ergonomics", "definition": "The study of preventing workplace injury and stress. In nursing, it refers to the way a nurse can prevent injury to self and others from the stressors and strains required in the field."},
    {"term": "Hazardous Materials", "definition": "Solids, liquids, or gases that are harmful to humans or the environment and may be soluble, ignitable, corrosive, reactive, or toxic."},
    {"term": "Incident Command System (ICS)", "definition": "A highly organized, hierarchical disaster response system developed by the Department of Homeland Security that focuses on planning, organization, communication, and delegation of responsibility."},
    {"term": "Infection Control Plan", "definition": "A surveillance plan whose primary purpose is to identify a means to decrease the rates of infection in a healthcare facility and evaluate the effectiveness of control measures."},
    {"term": "Mass-Casualty Incidents", "definition": "Incidents involving more than one person that may involve dozens, hundreds, or thousands of victims and require the response of multiple jurisdictions and agencies."},
    {"term": "Medication Errors", "definition": "There are about 7,000 deaths yearly in the United States attributed to these errors. Prevention involves careful handling and administration of medications."},
    {"term": "Multiple-Casualty Incidents", "definition": "Incidents involving more than one person, usually at least three patients, that require a response from one to three agencies (e.g., ambulance, fire department, police)."},
    {"term": "Nosocomial Infections", "definition": "Healthcare-associated or hospital-acquired infections. Common types include enterococci infections, Escherichia coli, Group B-hemolytic Streptococcus, MRSA, and Aspergillus spp."},
    {"term": "P.A.S.S.", "definition": "An acronym used for fire extinguisher safety: Pull the pin, Aim at the base of the flames, Squeeze the trigger, and Sweep using a sweeping motion across the flames."},
    {"term": "R.A.C.E.", "definition": "An acronym used for fire safety in the hospital unit: Rescue, Activate alarm, Contain, and Evacuate/Extinguish."},
    {"term": "Safety Data Sheet (SDS)", "definition": "A document that must be readily available for all hazardous materials, providing information on their properties and potential hazards."},
    {"term": "Seizure Precautions", "definition": "A safety protocol that ensures patient safety for those with a high risk of seizures. This includes padding side rails, keeping the bed in the lowest position, and maintaining suctioning at the bedside."},
    {"term": "Terrorism", "definition": "The use of violence or the threat of violence to frighten and coerce governments or societies, often focused on areas with high population densities."},
    {"term": "Triage", "definition": "A method of prioritizing clients based on the severity of their conditions and the likelihood of their survival in a mass casualty incident. It is categorized into P1-Red (immediate), P2-Yellow (delayed), P3-Green (minor), and P4-Black (deceased)."}
  ]'::jsonb
)
ON CONFLICT DO NOTHING;

-- Insert Episode 4 study guide
INSERT INTO study_guides (episode_id, title, short_answer_questions, essay_questions, glossary)
VALUES (
  4,
  'Health Promotion and Maintenance: A Study Guide',
  '[
    {"question": "Differentiate between the terms \"immunization\" and \"vaccination\" as defined in the text.", "answer": "Immunization refers to the body''s process of building up antibodies against specific diseases, which is important for preventing the spread of infection. Vaccination is one specific method of creating this immunity by introducing an antigen—a killed or weakened form of a virus or bacteria—to stimulate the body''s production of antibodies without causing the disease itself."},
    {"question": "Describe three distinct types of vaccines and how they function.", "answer": "Three types of vaccines include the live virus, toxoid, and killed virus forms. A live virus vaccine uses a weakened (attenuated) form of the virus that doesn''t cause the disease but confers immunity (e.g., measles vaccine). A toxoid is a toxin that has been weakened by heat or chemicals, making it too weak to cause disease but still able to stimulate an immune response. A killed virus vaccine contains a virus that has been killed, which triggers an immune response without any risk of causing the illness."},
    {"question": "According to Erikson''s developmental tasks, what is the central conflict during infancy (birth to 1 year) and adolescence (ages 12-18)?", "answer": "During infancy (birth to 1 year), the central conflict is Trust vs. Mistrust, where the infant develops trust and optimism if their needs for warmth, food, and love are met. During adolescence (ages 12-18), the conflict is Identity vs. Role Confusion, where teenagers, influenced by peers and family, learn to discover their own identity."},
    {"question": "What is the biopsychosocial theory of patient care, and what does it recommend for treatment?", "answer": "The biopsychosocial theory recognizes that biology, psychology, and social circumstances all contribute to a patient''s perception of an illness and their ability to recover. It recommends a multidisciplinary approach where a healthcare team, including nurses, mental health professionals, and physicians, works together to address all aspects of a patient''s problem to find an integrated solution, such as combining medical treatment with stress-reduction and exercise."},
    {"question": "List the five main goals of the Healthy People 2030 initiative.", "answer": "The five main goals are: (1) Attaining healthy, thriving lives free of preventable disease, disability, injury, and premature death; (2) Eliminating health disparities and achieving health equity; (3) Creating social and physical environments that promote good health; (4) Promoting quality of life and healthy behaviors in all life stages; (5) Engaging with leadership to create policies that improve health."},
    {"question": "Explain the difference between primary, secondary, and tertiary prevention strategies.", "answer": "Primary prevention measures are used in health populations before disease onset to prevent it from occurring. Secondary prevention measures are used to screen, detect, and treat disease in its earliest stages to prevent further progression. Tertiary prevention strategies are used to prevent the onset of other complications or comorbid conditions in those who already have a disease."},
    {"question": "What are the three primary components of a risk analysis for assessing and managing a child''s health?", "answer": "The three primary components are: (1) Assessing, which involves gathering information by questioning, observing, or analyzing data; (2) Intervening, which involves taking action based on the assessment, such as making changes in management or treatments; and (3) Communicating, which requires publishing results or sharing them with the family, organization, or public to determine the scope of the risk analysis."},
    {"question": "Describe the key characteristics of Fetal Alcohol Syndrome (FAS) and the related condition known as ARND.", "answer": "Fetal Alcohol Syndrome is a pattern of birth defects from maternal alcohol ingestion, resulting in facial abnormalities (e.g., hypoplastic maxilla, micrognathia), neurological problems (e.g., intellectual disability, motor delay), and behavioral problems (e.g., irritability, hyperactivity). Alcohol-related neurodevelopmental disorder (ARND) refers to the indication of brain damage without the associated physical abnormalities of FAS."},
    {"question": "According to the Youth Risk Behavior Surveillance System (YRBSS), what are the top two leading causes of death for the 11- to 24-year-old age group?", "answer": "For the 11- to 24-year-old age group, the leading cause of death is unintentional accidents, such as motor vehicle accidents. The second leading cause of death in this age group is homicide, which is often followed by suicide as the third leading cause."},
    {"question": "Summarize the essential guidelines for positioning an infant to sleep safely to reduce the risk of Sudden Infant Death Syndrome (SIDS).", "answer": "To reduce the risk of SIDS, infants should be placed on their backs for sleeping. The infant should be positioned on a firm surface, with their head to one side to prevent positional molding. They should not be placed on their stomach or in a side-lying position unless a specially designed monitor is used to maintain that position."}
  ]'::jsonb,
  '[
    {"question": "Compare and contrast the primary arguments of the Nature vs. Nurture and Continuity vs. Discontinuity debates in human development theory. How do these differing perspectives influence the understanding of a child''s growth trajectory?", "guidance": "Formulate comprehensive essay response, synthesizing information from across the provided source materials."},
    {"question": "Using Maslow''s Hierarchy of Needs as a framework, analyze how the health risks associated with poverty—such as incomplete immunizations, frequent infections, poor nutrition, and lack of safety—can impact a child''s ability to achieve higher-level needs like \"Love/Belonging\" and \"Esteem.\"", "guidance": "Formulate comprehensive essay response, synthesizing information from across the provided source materials."},
    {"question": "Discuss the comprehensive approach to injury prevention for children from toddlerhood through adolescence as outlined in the text. Detail specific safety measures recommended for different age groups regarding home, auto, sports, and social situations.", "guidance": "Formulate comprehensive essay response, synthesizing information from across the provided source materials."},
    {"question": "Explain the concept of herd immunity and its importance in public health. Then, describe the anti-vaccination movement and the recommended course of action for healthcare professionals when caregivers refuse vaccinations for their children.", "guidance": "Formulate comprehensive essay response, synthesizing information from across the provided source materials."},
    {"question": "Detail the various types of health screenings recommended for young adults (age 20-39) and adults (age 40 and older). Explain the purpose of key screenings like blood pressure checks, Pap smears, mammograms, and colorectal cancer screenings, and discuss their recommended frequencies.", "guidance": "Formulate comprehensive essay response, synthesizing information from across the provided source materials."}
  ]'::jsonb,
  '[
    {"term": "Anti-Vaccination Movement", "definition": "A movement that has gained momentum through social media, opposing vaccination based on beliefs that the risks of vaccines outweigh the benefits, particularly in infancy and early childhood."},
    {"term": "Biopsychosocial Theory", "definition": "A theory of patient care that recognizes that biology, psychology, and social circumstances all contribute to a patient''s perception of an illness and their ability to make a full and speedy recovery."},
    {"term": "Conjugated Form (Vaccine)", "definition": "A type of vaccine where an organism is altered and then joined (conjugated) with another substance to provoke an immune response, such as in the conjugated Hib vaccine."},
    {"term": "Erikson''s Developmental Tasks", "definition": "A theory outlining eight developmental stages from infancy to old age, each characterized by a central psychosocial conflict that must be resolved (e.g., Trust vs. Mistrust)."},
    {"term": "Fetal Alcohol Syndrome (FAS)", "definition": "A pattern of birth defects that develops as a result of maternal ingestion of alcohol, characterized by facial, neurological, and behavioral abnormalities."},
    {"term": "Freud''s Stages of Psychosexual Development", "definition": "A theory describing five stages (oral, anal, phallic, latency, genital) where a child''s focus is on a different part of the body, and these stages must be met for proper psychosexual development."},
    {"term": "Herd Immunity", "definition": "A form of indirect protection from infectious disease that occurs when a sufficient percentage of a population has become immune, either through vaccination or previous infections, thereby reducing the likelihood of infection for individuals who lack immunity. The text specifies this range is typically 83-94%."},
    {"term": "Immunization", "definition": "The body''s buildup of defense (antibodies) against specific diseases, which plays an important role in preventing the spread of infection."},
    {"term": "Killed Virus Vaccine", "definition": "A vaccine in which the virus has been killed but is still capable of eliciting an immune response (e.g., inactivated poliovirus)."},
    {"term": "Live Virus Vaccine", "definition": "A vaccine that uses a live but weakened (attenuated) form of a virus so that it doesn''t cause the disease but confers immunity (e.g., measles vaccine)."},
    {"term": "Maslow''s Hierarchy of Needs", "definition": "A theory that portrays human motivation as a pyramid with five levels of needs, from basic physiological needs at the bottom to self-actualization at the top."},
    {"term": "Piaget''s Theory of Cognitive Development", "definition": "A theory stating that development is progressive and follows a set pattern through four stages: sensorimotor, preoperational, concrete operations, and formal operations."},
    {"term": "Primary Prevention", "definition": "Disease prevention measures employed prior to disease onset and used in health populations."},
    {"term": "Recombinant Form (Vaccine)", "definition": "A vaccine in which the organism is genetically altered and may use proteins rather than the whole cell to confer immunity (e.g., Hepatitis B)."},
    {"term": "Risk Analysis", "definition": "An important part of health promotion and disease prevention that can help identify those at high risk for current or future disease. Its three components are assessing, intervening, and communicating."},
    {"term": "Secondary Prevention", "definition": "Disease prevention measures used to screen, detect, and treat disease in earlier stages to prevent further progression or development of other complications."},
    {"term": "Selye''s Theory of Adaptation", "definition": "A theory describing a person''s physiologic response to stress, called the general adaptation syndrome, which starts with the \"fight or flight\" response."},
    {"term": "Shaken Baby Syndrome", "definition": "A condition believed to be the result of vigorous shaking of a neonate, causing acute subdural hematoma with subarachnoid and retinal hemorrhages, leading to damage to vessels and neurons."},
    {"term": "Sudden Infant Death Syndrome (SIDS)", "definition": "A leading cause of infant death. The risk is increased by sleeping on the stomach, which is why infants should be placed on their backs to sleep."},
    {"term": "Tertiary Prevention", "definition": "Disease prevention measures used to prevent the onset of other complications or comorbid conditions."},
    {"term": "Toxoid", "definition": "A toxin (antigen) that has been weakened by the use of heat or chemicals so it is too weak to cause disease but stimulates antibodies."},
    {"term": "Vaccination", "definition": "One method of creating immunity by introducing an antigen (a killed or weakened virus or bacteria) to stimulate the body to produce its own antibodies."},
    {"term": "Youth Risk Behavior Surveillance System (YRBSS)", "definition": "A program conducted through the CDC that monitors eight different categories of health-risk behaviors of adolescents to assess prevalence and trends."}
  ]'::jsonb
)
ON CONFLICT DO NOTHING;
-- Insert Episode 5: Psychosocial Integrity
-- Insert Episode 6: Basic Care and Comfort  
-- Insert Episode 7: Pharmacology
-- Insert Episode 8: Pharmacological Therapies
-- (Simplified inserts - full data will be added via admin interface after migration runs)
