-- Insert Episode 7: Pharmacology
INSERT INTO study_guides (episode_id, title, short_answer_questions, essay_questions, glossary)
VALUES (
  7,
  'Pharmacology Study Guide',
  '[
    {"question": "Differentiate between the core principles of pharmacokinetics and pharmacodynamics.", "answer": "Pharmacokinetics relates to the route of administration, absorption, dosage, and the frequency of administration, describing how the body processes a drug over time. Pharmacodynamics, in contrast, relates to the biological and therapeutic effects of the drug on the body, including side effects and how the drug''s effect changes with its concentration."},
    {"question": "What are the \"5 rights\" of medication administration and what is their purpose?", "answer": "The \"5 rights\" are: Right Patient, Right Drug, Right Dose, Right Route, and Right Time/Frequency. They are a set of medication administration guidelines used to prevent medication errors in a hospital setting and are often integrated into electronic documentation."},
    {"question": "Explain the concept of \"first-pass metabolism\" and list three administration routes that avoid it.", "answer": "First-pass metabolism occurs when ingested drugs absorbed through the gastrointestinal tract travel to the liver via the portal system, where they are broken down before reaching systemic circulation, reducing the active drug amount. Administration routes that avoid this process include intravenous, intramuscular, and sublingual."},
    {"question": "Describe the primary function of inotropic agents and provide an example of a β-adrenergic agonist.", "answer": "Inotropic agents are drugs used to increase cardiac output and improve contractility. An example of a β-adrenergic agonist, a type of inotropic agent, is Dobutamine, which helps the body to imitate norepinephrine effects, increase cardiac output, and treat cardiac decomposition."},
    {"question": "What are the initial, early signs of digoxin toxicity?", "answer": "The early signs of digoxin toxicity include increasing fatigue, followed by anorexia, dehydration, and nausea and vomiting. As toxicity progresses to severe diarrhea, blurred vision, or yellow/green halos around lights, the patient may also experience fatigue and weakness."},
    {"question": "How do corticosteroids function as a pharmacological agent for asthma?", "answer": "Corticosteroids provide an anti-inflammatory action by inhibiting immune responses and decreasing edema, mucus, and hyper-responsiveness. They are used in both long-acting preventative treatments and for acute exacerbations of asthma."},
    {"question": "Define palliative sedation and differentiate it from euthanasia.", "answer": "Palliative sedation is a treatment method focused on controlling and easing symptoms that have proven resistant to other treatments, with the goal of providing comfort. The text emphasizes that the process is focused on symptom management and must be clearly distinguished from euthanasia."},
    {"question": "According to the text, what are three absolute contraindications for administering fibrinolytic agents?", "answer": "Absolute contraindications for administering fibrinolytic agents include any present or recent bleeding or history of severe bleeding, history of intracranial hemorrhage, and suspected aortic dissection or pericarditis. A recent stroke (within 3 hours) is also an absolute contraindication."},
    {"question": "Explain the primary risk associated with the anticoagulant heparin and describe its antidote.", "answer": "The major risk factor associated with heparin use is hemorrhage. Heparin is an anticoagulant derived from the intestinal mucosa of pigs and the lung tissue of pigs. The effects of heparin can be reversed by its antidote, protamine sulfate."},
    {"question": "What is neutropenia and why is it a significant concern for patients undergoing chemotherapy?", "answer": "Neutropenia is a common chemotherapy concern characterized by a decreased number of neutrophils in the patient''s system. It is considered a silent but dangerous risk because neutrophils are needed to fight the threat of infections, leaving the patient highly susceptible."}
  ]'::jsonb,
  '[
    {"question": "Compare and contrast the mechanisms, uses, side effects, and specific examples of three different classes of diuretics: Loop Diuretics, Thiazide Diuretics, and Potassium-Sparing Diuretics.", "guidance": "Synthesize information from across the source material to formulate a comprehensive answer."},
    {"question": "A patient with coronary artery disease requires medication. Using the source text, discuss the pharmacodynamics of three different drug classes that could be used (e.g., Calcium Channel Blockers, ACE inhibitors, β-blockers), explaining how each class works to treat the condition and what potential side effects must be monitored.", "guidance": "Synthesize information from across the source material to formulate a comprehensive answer."},
    {"question": "Describe the complete process of oral drug administration and its journey through the body. Incorporate the principles of absorption, distribution, first-pass metabolism, enterohepatic recirculation, drug clearance, and excretion as detailed in the text.", "guidance": "Synthesize information from across the source material to formulate a comprehensive answer."},
    {"question": "Analyze the challenges of managing drug therapy by explaining the different types of drug interactions (pharmacodynamic and pharmacokinetic). Provide specific examples of how interactions can alter a drug''s absorption, distribution, metabolism, and excretion.", "guidance": "Synthesize information from across the source material to formulate a comprehensive answer."},
    {"question": "Discuss the various routes of delivery for chemotherapy agents. Explain why different routes are chosen based on the cancer type and location, and detail the common side effects and serious risks (e.g., cardiotoxicity, nephrotoxicity, neutropenia) associated with these powerful drugs.", "guidance": "Synthesize information from across the source material to formulate a comprehensive answer."}
  ]'::jsonb,
  '[
    {"term": "Absorption", "definition": "The rate of a drug depends on its transfer from its site of administration to the circulatory system. Different routes of administration have different absorption characteristics."},
    {"term": "ACE Inhibitors", "definition": "A class of anti-hypertensive medications that prevent the conversion of angiotensin I to angiotensin II, leading to vasodilation. Examples include benazepril and captopril."},
    {"term": "Agonist", "definition": "Drugs that exert effects after binding with a receptor."},
    {"term": "Alkylating agents", "definition": "Chemotherapeutic agents that work by directly attacking the DNA of cancers."},
    {"term": "Antagonist", "definition": "Drugs that prevent other drugs from binding with a receptor."},
    {"term": "Anticoagulants", "definition": "Drugs used at home and in the hospital setting to prevent blood clots from forming. Examples include Heparin and Warfarin."},
    {"term": "Anti-dysrhythmic Drugs", "definition": "Drugs that act on the conduction system, the ventricles, and/or the atria to control dysrhythmias."},
    {"term": "Bioavailability", "definition": "A drug''s ability to be absorbed. May vary depending upon the degree of metabolism that takes place before the drug reaches its site of action."},
    {"term": "Chemotherapy", "definition": "A treatment offered during palliative care to enhance patient comfort, well-being, and symptom control, which is not expected to preserve or prolong life."},
    {"term": "Context-sensitive half-life", "definition": "The time needed to reach 50% concentration after withdrawal of a continuously infused drug."},
    {"term": "Drug Clearance", "definition": "The removal of a drug from the body. The two main organs responsible are the liver and the kidneys."},
    {"term": "Elimination half-life", "definition": "The time needed for the concentration of a particular drug to decrease to half of its starting dose in the body. Approximately five half-lives are needed to achieve steady-state plasma concentration or to eliminate a drug."},
    {"term": "Enterohepatic Recirculation", "definition": "A process whereby a drug is effectively reabsorbed from circulation and then reabsorbed. This process increases the duration of action for drugs with a molecular weight greater than 300 g/mol and those that are amphipathic."},
    {"term": "Fibrinolytic Agents", "definition": "Drugs that should be administered as soon as possible (within 30 minutes is best) to convert plasminogen to plasmin, which breaks down fibrin, dissolving clots."},
    {"term": "First-Pass Metabolism", "definition": "The breakdown of orally ingested drugs that occurs in the liver after being absorbed through the gastrointestinal tract, before reaching systemic circulation."},
    {"term": "Generic name", "definition": "A simpler name for a drug. A company making the drug can give it a brand name, but the generic name is related to the chemical name."},
    {"term": "Heparin", "definition": "An anticoagulant derived from the intestinal mucosa of the pig and the lung-like pig tissue, which inhibits thrombin and other clotting proteases."},
    {"term": "Inotropic Agents", "definition": "Drugs used to increase cardiac output and improve contractility."},
    {"term": "Neutropenia", "definition": "A decreased number of neutrophils in the patient''s system, a common concern of chemotherapy because it leaves the patient susceptible to infections."},
    {"term": "Palliative Sedation", "definition": "A treatment method focused on controlling and easing symptoms that have proven resistant to other treatments, with the goal of providing comfort rather than prolonging life."},
    {"term": "Pharmacodynamics", "definition": "Relates to biological effects (therapeutic or adverse) of drug administration over time."},
    {"term": "Pharmacokinetics", "definition": "Relates to the route of administration, the absorption, the dosage, the frequency of administration, and how serum levels are achieved over time."},
    {"term": "Recovery time", "definition": "The length of time it takes for plasma levels to decrease to the point that the effect is eliminated."},
    {"term": "Steady state", "definition": "The point at which the drug reaches the appropriate receptors and must be considered when determining dose, time, and frequency of medication."},
    {"term": "Thrombolytics", "definition": "Drugs used to dissolve clots for myocardial infarction, ischemic stroke, DVT, and pulmonary embolism. Examples include alteplase, reteplase, streptokinase, and tenecteplase."},
    {"term": "Volume of distribution", "definition": "The rate at which the drug passes into tissue, which depends on the degree of protein binding and ion trapping of the molecule."},
    {"term": "Warfarin", "definition": "An anti-thrombotic agent that causes a deficiency in prothrombin in the plasma. It works by inhibiting the action of vitamin K."}
  ]'::jsonb
)
ON CONFLICT DO NOTHING;

-- Insert Episode 8: Pharmacological Therapies
INSERT INTO study_guides (episode_id, title, short_answer_questions, essay_questions, glossary)
VALUES (
  8,
  'Study Guide: Pharmacological Therapies',
  '[
    {"question": "What is the purpose of the MASTER rules, and what does the acronym stand for?", "answer": "The MASTER rules are a set of guidelines for rational drug therapy, designed to improve safety and efficacy when treating diseases. The acronym stands for Minimize the number of drugs, Alternatives should be considered, Start low and go slow, Titrate to the individual patient, Educate the patient, and Review regularly."},
    {"question": "Explain the primary mechanism of action for Monoamine Oxidase Inhibitors (MAOIs) and describe the most dangerous side effect associated with them.", "answer": "MAOIs work by inhibiting the monoamine oxidase enzyme, which increases the levels of serotonin and norepinephrine available for neurotransmission. The most dangerous side effect is an extreme elevation in blood pressure, or hypertensive crisis, which can occur when a patient on MAOIs consumes foods high in tyramine."},
    {"question": "Describe the three steps of the WHO pain ladder for pharmacologic pain management.", "answer": "The WHO pain ladder is a three-step algorithm for treating pain. Step 1 involves using a non-opioid analgesic. Step 2, for mild-to-moderate-level pain, adds a relieving-opioid medication. Step 3 is initiated for uncontrolled or moderate-to-severe pain and involves treatment with opioids."},
    {"question": "What is polypharmacy, and why does it present a significant risk, particularly for geriatric patients?", "answer": "Polypharmacy is the inappropriate use of multiple medications at one time, particularly when medications are taken that are not indicated. This greatly increases the risk of adverse drug reactions, a risk that is already elevated in geriatric patients due to physiological changes."},
    {"question": "How do Proton Pump Inhibitors (PPIs) work to treat gastrointestinal issues, and how does their use compare to Histamine receptor antagonists?", "answer": "PPIs inhibit an enzyme in the stomach wall, which reduces stomach acid and helps treat GERD and peptic ulcers. They are now used more frequently than histamine receptor antagonists because they are more effective."},
    {"question": "Distinguish between addiction and pseudoaddiction as they relate to pain medication.", "answer": "Addiction is a primary and constant neurologic disease characterized by compulsive and persistent use of a drug despite harmful consequences. Pseudoaddiction is an assumption that a patient is addicted when, in reality, the patient is experiencing undertreated pain, which may cause them to become more aggressive in seeking medicated relief."},
    {"question": "What are extrapyramidal effects, and which class of medications is most commonly associated with them?", "answer": "Extrapyramidal effects are a group of neural side effects that impact motor function, including akinesia, akathisia, and dystonia, which are caused by drug influence on the extrapyramidal system. These effects are a common side effect of first-generation antipsychotic medications."},
    {"question": "How does Hypertonic Saline Solution (HSS) function to treat conditions like traumatic brain injury?", "answer": "HSS has a sodium concentration higher than 0.9% and is used to reduce intracranial pressure and treat traumatic brain injury. It works by drawing edema out of the brain tissue, expanding plasma, and counteracting the hyponatremia that can occur after a brain injury."},
    {"question": "Identify four key pharmacokinetic processes that are altered in elderly adults and can affect medication efficacy and safety.", "answer": "In elderly adults, pharmacokinetic processes are altered in four key ways: absorption may be delayed or decreased due to blood flow changes; distribution is altered due to changes in body composition; metabolism by the liver or kidneys is decreased; and final function and elimination effectiveness is often decreased due to declining kidney ability."},
    {"question": "Name the three basic types of breakthrough pain and briefly describe one of them.", "answer": "The three types of breakthrough pain are incident pain, spontaneous pain, and end-of-dose failure pain. Incident pain can be specifically tied to an activity or event, such as a dressing change or physical therapy, and can be anticipated and treated with a rapid-onset, short-acting medication."}
  ]'::jsonb,
  '[
    {"question": "Compare and contrast the mechanisms of action, primary uses, and significant side effect profiles of the three major classes of antidepressants discussed: SSRIs, Tricyclic Antidepressants, and MAOIs.", "guidance": "Formulate comprehensive responses to the following prompts, synthesizing information from across the source material."},
    {"question": "Discuss the comprehensive approach to pharmacologic pain management. Your answer should incorporate the principles of the WHO Pain Ladder, the rationale for scheduling pain medications versus PRN (as needed) use, and strategies for treating different types of pain, including neuropathic, bone, and breakthrough pain.", "guidance": "Formulate comprehensive responses to the following prompts, synthesizing information from across the source material."},
    {"question": "Explain the unique challenges and considerations in medication management for elderly patients. Address the four major pharmacokinetic changes, the concept and risks of polypharmacy, and the purpose of the Beers Criteria.", "guidance": "Formulate comprehensive responses to the following prompts, synthesizing information from across the source material."},
    {"question": "Analyze the complexities surrounding opioid use for pain management. Cover the side effects that impact various body systems, the phenomena of tolerance and physical dependence, and the critical distinctions between addiction, pseudoaddiction, and pseudotolerance.", "guidance": "Formulate comprehensive responses to the following prompts, synthesizing information from across the source material."},
    {"question": "Describe the MASTER rules for rational drug therapy. For each principle in the acronym, explain how its application can mitigate common pharmacological problems such as drug interactions, adverse effects, and drug intolerance, particularly in patients with complex medical needs.", "guidance": "Formulate comprehensive responses to the following prompts, synthesizing information from across the source material."}
  ]'::jsonb,
  '[
    {"term": "Addiction", "definition": "A primary and constant neurologic disease with genetic, psychosocial, and environmental factors as contributors. It is characterized by behaviors that include untreated, continued cravings, as well as compulsive and persistent use of a drug despite harmful repercussions and side effects."},
    {"term": "Antacids", "definition": "Medications used to treat heartburn or indigestion by raising the pH and neutralizing the acid present in the stomach."},
    {"term": "Anticonvulsants", "definition": "A class of drugs used to treat various types of seizures."},
    {"term": "Antidepressants", "definition": "A class of drugs for which the main indicator is depression. They are also used for anxiety disorders."},
    {"term": "Anti-lipids", "definition": "Medications used to lower cholesterol levels when dietary modifications are insufficient."},
    {"term": "Antipsychotic Medications", "definition": "Drugs used to treat psychosis. First-generation antipsychotics are becoming less prominent than newer atypical (second-generation) antipsychotics."},
    {"term": "Beers Criteria", "definition": "A list that identifies inappropriate medication use among older adults. It is used to determine which medications are beneficial compared to those that impose risks for older adults."},
    {"term": "Benzodiazepines", "definition": "The most commonly prescribed medications for anxiety, which enhance the neurotransmitter GABA to inhibit the firing rate of neurons."},
    {"term": "Bile Acid Sequestrants", "definition": "A type of anti-lipid that binds bile acids in the intestine, which the liver then has to produce more bile acids from cholesterol, lowering cholesterol levels."},
    {"term": "Breakthrough Pain", "definition": "Pain that occurs specifically at the end of a routine analgesic dosing cycle when blood levels begin to taper off."},
    {"term": "Extrapyramidal Effects", "definition": "A group of neural side effects that impact motor function and movement. Common with first-generation antipsychotics."},
    {"term": "Histamine (H2) Receptor Antagonists", "definition": "A class of drugs that treat conditions where excessive stomach acid causes heartburn and GERD by blocking H2 parietal cell receptors in the stomach."},
    {"term": "Hypertonic Saline Solution (HSS)", "definition": "A saline solution with a sodium concentration higher than 0.9% used to reduce intracranial pressure/cerebral edema and treat traumatic brain injury."},
    {"term": "Ketamine", "definition": "A dissociative anesthetic that can provide pain relief as an alternate or complement to an opioid."},
    {"term": "Laxatives", "definition": "A category of drugs with different types, including bulk formers, lubricants, saline, stool softeners, hyperosmolar, and stimulants, used to treat constipation."},
    {"term": "Local Anesthetic Pain Relief", "definition": "The neural conduction of pain is blocked through the application of the anesthetic directly to the nerve endings in the area of pain."},
    {"term": "Mannitol", "definition": "An osmotic diuretic that increases excretion of both sodium and water and reduces intracranial pressure. It helps other medications breach the blood-brain barrier."},
    {"term": "MAOIs (Monoamine Oxidase Inhibitors)", "definition": "A class of antidepressants that inhibit the enzyme monoamine oxidase, increasing levels of serotonin and norepinephrine. Patients must follow a low-tyramine diet."},
    {"term": "MASTER Rules", "definition": "An acronym for rules of rational drug therapy: Minimize drugs, Alternatives, Start low and go slow, Titrate, Educate, Review regularly."},
    {"term": "Neuropathic Pain", "definition": "A type of pain often treated with different medications than other types of pain, including anticonvulsants, anesthetics, and antidepressants."},
    {"term": "NSAIDs (Nonsteroidal Anti-inflammatory Drugs)", "definition": "A class of drugs that work by inhibiting cyclooxygenase (COX) enzymes, which controls prostaglandin formation. Used to treat pain, inflammation, and fever."},
    {"term": "Opioid Analgesic Therapy", "definition": "A widely used method of chronic pain control that, by adhering to clinical guidelines, can be safely optimized."},
    {"term": "Pharmacokinetics", "definition": "The four-step process involving absorption, distribution, metabolism, and elimination of drugs. These processes are often altered in elderly adults."},
    {"term": "Physical Dependence", "definition": "A condition where the body adapts to a drug, requiring increasing dosages over time to gain the same effect, and withdrawal of that drug will result in an abstinence syndrome (withdrawal)."},
    {"term": "Polypharmacy", "definition": "The inappropriate use of multiple medications at one time, particularly when medications are taken that are not indicated, or that have adverse interactions with one another."},
    {"term": "Proton Pump Inhibitors (PPIs)", "definition": "Drugs that are now used more often than histamine receptor antagonists to treat GERD and peptic ulcers by reducing stomach acid."},
    {"term": "Pseudoaddiction", "definition": "An assumption that the patient is addicted to a substance when in actuality the patient is experiencing undertreatment of unrelieved pain, leading them to be more aggressive in seeking relief."},
    {"term": "Pseudotolerance", "definition": "An unguided perception of the health care provider that a patient''s need for increasing doses of a drug is due to the development of tolerance, when the reality is that the disease progression or other factors are responsible."},
    {"term": "Serotonin Antagonists", "definition": "Drugs that block the receptor of serotonin in the central and peripheral nervous systems, used to prevent and treat nausea and vomiting."},
    {"term": "SSRIs (Selective Serotonin Reuptake Inhibitors)", "definition": "A class of antidepressants that prevent the reuptake of serotonin at the presynaptic membrane, making it more available for neurotransmission."},
    {"term": "Statins", "definition": "A class of anti-lipid medications (3-hydroxy-3-methylglutaryl coenzyme A reductase inhibitors) that are the primary option in the ability to reduce cholesterol."},
    {"term": "Tolerance", "definition": "The adaptation of the body to continued exposure to a drug or chemical, where the effects of the drug at the same level of exposure are minimized over time."},
    {"term": "Tricyclic Antidepressants", "definition": "A class of antidepressants that block the reuptake of serotonin and norepinephrine; however, their exact mechanism is unknown."},
    {"term": "WHO Pain Ladder", "definition": "An algorithm that was developed as an algorithm for treating pain through medications with progressively increasing potency."}
  ]'::jsonb
)
ON CONFLICT DO NOTHING;
