-- Insert Episode 9: Diagnostic Procedures and Pathophysiological Adaptations
INSERT INTO study_guides (episode_id, title, short_answer_questions, essay_questions, glossary)
VALUES (
  9,
  'Study Guide: Diagnostic Procedures and Pathophysiological Adaptations',
  '[
    {"question": "What is the key difference in pathophysiology between a NSTEMI and a STEMI?", "answer": "A Non-ST-segment elevation MI (NSTEMI) involves a partial blockage of coronary arteries with associated ST depression and T-wave inversion on an ECG. A ST-segment elevation MI (STEMI) is a more severe type caused by a complete blockage of one or more coronary arteries, resulting in ST elevation on an ECG and requiring immediate reperfusion."},
    {"question": "Describe the purpose of an Ankle-Brachial Index (ABI) and how the basic result is interpreted.", "answer": "The Ankle-Brachial Index (ABI) is a procedure used to evaluate peripheral arterial disease in the lower extremities. The result is calculated by dividing the ankle systolic pressure by the brachial systolic pressure. A score below 0.5 indicates severe arterial disease, while a score of 0.9-1.0 is considered low but acceptable."},
    {"question": "What are the three components of Virchow''s triad, and what condition do they predispose an individual to?", "answer": "Virchow''s triad describes three common risk factors for acute venous thromboembolism (VTE): hemodynamic changes (stasis), hypercoagulability, and endothelial injury/dysfunction. These factors increase the risk of forming a thrombus, such as a deep vein thrombosis (DVT)."},
    {"question": "Explain the function of capnography and what a typical end-tidal CO₂ (ETCO₂) value indicates.", "answer": "Capnography measures the concentration of CO₂ in expired air using an end-tidal CO₂ (ETCO₂) detector, which changes from purple to yellow in the presence of CO₂. A normal ETCO₂ value is 35-45 mmHg, and the waveform is used to confirm endotracheal tube placement and monitor ventilation."},
    {"question": "How do the S1 and S2 heart sounds originate, and what areas are best for auscultation?", "answer": "The S1 sound, or \"lub,\" is caused by the closure of the mitral and tricuspid valves and is best heard at the apex of the heart. The S2 sound, or \"dub,\" is caused by the closure of the aortic and pulmonic valves and is best heard at the base of the heart."},
    {"question": "What is the significance of elevated troponin I and troponin T levels in a patient assessment?", "answer": "Troponin I and T are proteins released into the bloodstream following myocardial injury, as they are found in cardiac muscle. Elevated levels (e.g., Troponin I >1.5 ng/mL or Troponin T >0.2 ng/mL) are sensitive indicators used to diagnose acute coronary syndrome and myocardial infarction."},
    {"question": "Differentiate between a hypertensive emergency and a hypertensive urgency based on treatment goals.", "answer": "A hypertensive emergency involves an acute blood pressure elevation (e.g., >220/120 mmHg) that requires immediate treatment to prevent vital organ damage. A hypertensive urgency is less immediately dangerous, and blood pressure is lowered more slowly over a few hours to avoid hypoperfusion."},
    {"question": "What is the normal ventilation/perfusion (V/Q) ratio, and what does a low ratio suggest?", "answer": "The normal ventilation/perfusion (V/Q) ratio is 0.8, which represents a balance between air reaching the alveoli and blood perfusing them. A low V/Q ratio indicates that ventilation is too low or perfusion is too high, which can be caused by conditions like atelectasis or pneumonia."},
    {"question": "List the three parameters measured by the Glasgow Coma Scale (GCS) to assess a patient''s level of consciousness.", "answer": "The Glasgow Coma Scale (GCS) assesses level of consciousness using three parameters: eye opening, verbal response, and motor response. The best response in each category is scored, yielding a total score between 3 and 15."},
    {"question": "Compare albumin and prealbumin as laboratory markers for assessing a patient''s nutritional status.", "answer": "Albumin is a common screening tool for protein deficiency but has a long half-life (18-20 days), making it insensitive to short-term nutritional changes. Prealbumin is a better indicator for acute changes, as its half-life is only 2-3 days, and its levels rise quickly in response to increased protein intake."}
  ]'::jsonb,
  '[
    {"question": "A patient presents to the emergency department with acute chest pain, shortness of breath, and diaphoresis. Synthesize the diagnostic information from the text (including ECGs, cardiac enzymes, and imaging) to create a comprehensive differential diagnosis and workup plan for this patient.", "guidance": "The following questions are designed for a deeper, essay-format response."},
    {"question": "Compare and contrast systolic and diastolic heart failure. Discuss the underlying pathophysiology, typical patient populations, clinical symptoms, and primary treatment goals for each condition as outlined in the provided material.", "guidance": "The following questions are designed for a deeper, essay-format response."},
    {"question": "Explain the progression and clinical significance of atrioventricular (AV) blocks, from first-degree to third-degree (complete) block. Describe the characteristic ECG findings and potential patient symptoms for each type.", "guidance": "The following questions are designed for a deeper, essay-format response."},
    {"question": "Discuss the body''s methods of \"Physiological Airway Clearance\" and the primary and secondary muscles used for breathing. How can disruptions in these mechanisms, such as those caused by disease or postoperative states, lead to respiratory compromise?", "guidance": "The following questions are designed for a deeper, essay-format response."},
    {"question": "Using the provided information on liver function tests, coagulation profiles, and nutritional labs, construct a detailed profile of a patient with severe liver disease. Explain how the abnormalities in bilirubin, albumin, PT, ammonia, and platelets are interconnected and what they reveal about the patient''s condition.", "guidance": "The following questions are designed for a deeper, essay-format response."}
  ]'::jsonb,
  '[
    {"term": "ABI (Ankle-brachial index)", "definition": "A test done to evaluate peripheral arterial disease of the lower extremities by dividing the ankle systolic pressure by the brachial systolic pressure."},
    {"term": "Acute Coronary Syndrome (ACS)", "definition": "An impairment of blood flow through the coronary arteries, leading to ischemia and necrosis of the myocardium. It encompasses stable angina, unstable angina, and myocardial infarction."},
    {"term": "Albumin", "definition": "A protein produced by the liver, essential for cells and tissues. It is the most common screening tool for protein deficiencies but has a long half-life of 18-20 days."},
    {"term": "Alkaline phosphatase", "definition": "A liver function test value that, when elevated, may indicate biliary tract obstruction or bone disease."},
    {"term": "ALT (SGPT)", "definition": "A liver enzyme; increased levels may indicate liver cell damage."},
    {"term": "Anasarca", "definition": "Severe, generalized edema, which is a sign of third-spacing of fluid in heart failure."},
    {"term": "Angiogram", "definition": "A procedure that may be used to visualize vasculature. Post-procedure, the patient must keep the extremity straight for 6-8 hours."},
    {"term": "Aortic Stenosis", "definition": "A narrowing of the aortic valve that controls blood flow from the left ventricle, which can lead to increased afterload and a need for increased blood supply to the heart."},
    {"term": "Arterial Blood Gases (ABG)", "definition": "A test used to assess the effectiveness of oxygenation, ventilation, and acid-base status. It measures pH, PaCO₂, PaO₂, HCO₃⁻, and SaO₂."},
    {"term": "Atrial Fibrillation (A-fib)", "definition": "A rapid, disorganized atrial rhythm where blood pools in the atria, which can lead to thrombus formation. The ECG is characterized by a highly variable ventricular rate and fibrillatory (F) waves instead of P waves."},
    {"term": "Atrial Flutter (A-flutter)", "definition": "A dysrhythmia where the atria rate is 250-400 beats per minute, faster than the AV node can conduct. The ECG often shows a sawtooth pattern of flutter (F) waves."},
    {"term": "AV nodal reentry tachycardia", "definition": "A type of tachycardia that occurs when an impulse conducts to an area of the AV node and is then sent in a rapidly repeating cycle back to the same area and to the ventricles."},
    {"term": "Bigeminy", "definition": "A rhythm where every other beat is a premature ventricular contraction (PVC)."},
    {"term": "Bleeding time", "definition": "A test that is prolonged with thrombocytopenia, which can occur due to drugs and alcohol. The normal range is 2-9.5 minutes."},
    {"term": "Blood urea nitrogen (BUN)", "definition": "A measure of renal function. An increased BUN/creatinine ratio indicates dehydration, while a normal ratio with an elevated BUN and creatinine indicates intrinsic kidney disease."},
    {"term": "Bruits", "definition": "Sounds that may be auscultated over major arteries, indicating peripheral arterial disease."},
    {"term": "Bundle Branch Block", "definition": "A condition where there is a conduction delay in the bundle branches of the heart''s electrical system, either on the right (RBBB) or left (LBBB)."},
    {"term": "Capnography", "definition": "Utilizes an end-tidal CO₂ (ETCO₂) detector that measures the concentration of CO₂ in expired air to confirm endotracheal tube placement and monitor respiratory status."},
    {"term": "Capillary refill time", "definition": "An assessment of perfusion. Normal venous filling occurs within a few seconds, while arterial occlusion is indicated by times greater than 2 to 3 seconds."},
    {"term": "Cardiac Enzymes (CK, CK-MB)", "definition": "Proteins released into the blood after a myocardial injury. CK-MB levels rise within 4-6 hours of an MI, peak at 12-24 hours, and return to normal within 3-4 days."},
    {"term": "Cardiogenic Shock", "definition": "A life-threatening condition where the heart fails to pump enough blood to provide adequate circulation and oxygen. The primary cause is acute myocardial infarction."},
    {"term": "Creatinine", "definition": "A product of muscle breakdown; serum levels are used to assess renal function. Increased levels are associated with decreased renal function."},
    {"term": "C-reactive protein", "definition": "A protein produced during the acute phase of an inflammatory response. It is a helpful measure for the response to treatment for pyelonephritis and osteomyelitis."},
    {"term": "D-dimer test", "definition": "A test that measures cross-linked fibrin derivatives; used to diagnose pulmonary emboli."},
    {"term": "Dysrhythmias", "definition": "Abnormal heart rhythms."},
    {"term": "Echocardiography", "definition": "A non-invasive ultrasound technology used for screening and diagnosing anatomic heart abnormalities, blood flow, and valvular lesions. Types include 2D Echo, TEE, Doppler, and bubble study."},
    {"term": "Electrocardiogram (ECG)", "definition": "A graphic representation of the electrical activity of the heart, used to diagnose basic heart rhythms, dysrhythmias, and conditions like myocardial infarction."},
    {"term": "EGD (Esophagogastroduodenoscopy)", "definition": "A procedure using a flexible fiberscope to directly inspect the esophagus, stomach, and duodenum."},
    {"term": "Ejection click", "definition": "A brief, high-pitched sound heard after S1, often associated with aortic stenosis."},
    {"term": "Erythrocyte sedimentation rate (sed rate)", "definition": "A non-specific test that measures the distance erythrocytes fall in a vertical tube in one hour; it increases in response to infection and inflammation."},
    {"term": "First-degree AV block", "definition": "A condition where atrial impulses are conducted through the AV node to the ventricles at a slower-than-normal rate, resulting in a prolonged PR interval (>0.20 seconds)."},
    {"term": "Gallop rhythms (S3 and S4)", "definition": "Additional heart sounds. S3 can be normal in children but may indicate left ventricular failure in adults. S4 occurs before S1 and is associated with coronary artery disease, hypertension, or aortic valve stenosis."},
    {"term": "Glasgow Coma Scale (GCS)", "definition": "A tool used to measure the depth and duration of coma or impaired level of consciousness by assessing eye opening, verbal response, and motor response. Scores range from 3 to 15."},
    {"term": "Heart Failure", "definition": "A cardiac disease that includes disorders of contractions (systolic dysfunction) or filling (diastolic dysfunction) or both."},
    {"term": "Hematocrit", "definition": "Indicates the proportion of RBCs in a liter of blood, usually about 3 times the hemoglobin number."},
    {"term": "Hemoglobin", "definition": "A component of RBCs that carries oxygen and is decreased in anemia and increased in polycythemia."},
    {"term": "Hemoglobin A1c", "definition": "A lab test where a glucose molecule bonds to hemoglobin. It reflects the average blood glucose over a 3-month period and is used to monitor long-term diabetes management."},
    {"term": "Hypertensive emergency", "definition": "An acute hypertension event, usually with systolic >220 mmHg or diastolic >120 mmHg, that must be treated immediately to prevent organ damage."},
    {"term": "Hypertensive urgency", "definition": "An acute hypertension event that must be treated within a few hours but is less immediately dangerous, allowing for slower blood pressure reduction."},
    {"term": "Idioventricular rhythm", "definition": "A ventricular escape rhythm that occurs when Purkinje fibers below the AV node create an impulse because the SA and AV nodes fail to fire. The rate is slow (20-40 BPM)."},
    {"term": "Junctional rhythms", "definition": "A rhythm that occurs when the AV node becomes the pacemaker of the heart, typically because the sinus node fails."},
    {"term": "MAP (mean arterial pressure)", "definition": "The pressure shown throughout the cardiac cycle, commonly used to evaluate perfusion. A MAP of greater than 60 mmHg is required to perfuse vital organs."},
    {"term": "Mean corpuscular volume (MCV)", "definition": "A measure of the size of red blood cells, used to differentiate types of anemia."},
    {"term": "Mitral Insufficiency", "definition": "Occurs when the mitral valve fails to close completely, allowing backflow into the left atrium from the left ventricle during systole, decreasing cardiac output."},
    {"term": "Mitral Stenosis", "definition": "A narrowing of the mitral valve that allows blood to flow from the left atrium to the left ventricle, resulting in enlargement of the left ventricle."},
    {"term": "Murmurs", "definition": "Additional heart sounds caused by turbulent blood flow through stenotic or malfunctioning valves, congenital defects, or increased blood flow."},
    {"term": "Myocardial Infarction (MI)", "definition": "Necrosis (death) of heart muscle tissue due to a lack of oxygenated blood flow."},
    {"term": "Myoglobin", "definition": "A protein that increases within 1-4 hours after MI but is not specific to MI and can be used to rule one out."},
    {"term": "National Institutes of Health Stroke Scale (NIHSS)", "definition": "A scale used to assess neurological deficits from stroke. It comprises 11 sections with scores for each section ranging from 0 (normal) to 2, 3, or 4."},
    {"term": "NSTEMI", "definition": "Non-ST-segment elevation MI; a type of heart attack resulting from partial blockage of coronary arteries."},
    {"term": "Obstructive Shock", "definition": "Occurs when the preload (diastolic filling) of the right ventricle is obstructed in one or several ways, such as from a pulmonary embolism or cardiac tamponade."},
    {"term": "Opening snap", "definition": "An unusual high-pitched sound occurring after S2 with stenosis of the mitral valve from rheumatic heart disease."},
    {"term": "Oxygen saturation", "definition": "The percentage of oxygen attached to hemoglobin. Normal arterial saturation is >95%. Central venous oxygen saturation (ScvO2) is measured in the right atrium."},
    {"term": "Papillary muscle rupture", "definition": "A rare but often deadly complication of a myocardial infarct where the muscles attaching the mitral valve rupture, leading to severe mitral regurgitation."},
    {"term": "Pericardial friction rub", "definition": "An additional heart sound that may be caused by pericarditis."},
    {"term": "Peripheral Arterial Insufficiency", "definition": "A condition characterized by pain ranging from intermittent claudication to constant shooting pain, weak or absent pulses, and pale or shiny skin on the lower extremities."},
    {"term": "Peripheral Venous Insufficiency", "definition": "A condition characterized by aching/cramping, present pulses, skin discoloration, and edema in the lower extremities."},
    {"term": "Platelet count", "definition": "The number of platelets per microliter of blood. A count <50,000 may require transfusion, and a count >750,000 indicates increased clotting."},
    {"term": "PONV (Postoperative nausea and vomiting)", "definition": "A condition that occurs in about 20-30% of post-anesthesia patients and may be delayed up to 24 hours."},
    {"term": "Prealbumin", "definition": "A protein produced in the liver with a short half-life of 2-3 days, making it a good measurement for acute changes in nutritional status."},
    {"term": "Premature atrial contraction (PAC)", "definition": "An extra beat precipitated by an electrical impulse in the atria that occurs outside of the sinoatrial node."},
    {"term": "Premature junctional contraction (PJC)", "definition": "An impulse that starts at the AV node before the next normal sinus impulse is initiated."},
    {"term": "Premature ventricular contractions (PVC)", "definition": "Impulses that begin in the ventricles and are conducted through the ventricles before the next normal sinus impulse."},
    {"term": "Prothrombin time (PT)", "definition": "A coagulation test that increases with anticoagulation therapy, vitamin K deficiency, and liver disease. Normal range is 10-14 seconds."},
    {"term": "Pulmonic Stenosis", "definition": "A stricture of the pulmonary blood valve that controls blood flow from the right ventricle to the lungs, resulting in right ventricular hypertrophy."},
    {"term": "Q-wave MI", "definition": "A myocardial infarction characterized by a series of abnormal, deep Q waves on an ECG, usually prolonged, and resulting in necrosis."},
    {"term": "Red blood cells (RBCs)", "definition": "Erythrocytes; biconcave disks that contain hemoglobin and carry oxygen throughout the body."},
    {"term": "Reticulocyte count", "definition": "A measure of marrow production of red blood cells."},
    {"term": "Second-degree AV block", "definition": "Occurs when some of the atrial beats are blocked. Type I (Wenckebach) has a progressively lengthening PR interval until a QRS is dropped. Type II has a constant PR interval with unpredictably dropped QRS complexes."},
    {"term": "Sinus arrhythmia", "definition": "A rhythm resulting from irregular impulses from the sinus node, often paradoxical with respiration (increasing with inspiration, decreasing with expiration)."},
    {"term": "Sinus bradycardia", "definition": "A sinus node dysrhythmia characterized by a decreased rate of impulse from the sinus node, with a heart rate <60 BPM."},
    {"term": "Sinus pause", "definition": "Occurs when the sinus node fails to fire an impulse to stimulate heart contractions, so there is no P wave or QRS complex for a beat."},
    {"term": "Sinus tachycardia", "definition": "A sinus node dysrhythmia that occurs when the sinus node impulse increases in frequency, with a heart rate >100 BPM."},
    {"term": "STEMI", "definition": "ST-segment elevation MI; a type of heart attack resulting from a complete blockage of one or more coronary arteries."},
    {"term": "Stress Echocardiography", "definition": "Basic cardiac stress testing combined with exercise/drug simulation and exercise imaging testing."},
    {"term": "Supraventricular tachycardia (SVT)", "definition": "A dysrhythmia with a sudden onset and heart rate of 100-300 BPM that originates in the atria rather than the ventricles."},
    {"term": "Third-degree AV block", "definition": "A complete AV block with no clear relationship between P waves and QRS complexes, as there is AV dissociation."},
    {"term": "Thromboembolism", "definition": "Includes both the formation of a thrombus (such as DVT) and an embolus (such as a pulmonary embolism)."},
    {"term": "Thrombin clotting time (TT)", "definition": "A coagulation test used to assess the dosage of heparin. It is prolonged with multiple myeloma, abnormal fibrinogen, uremia, and liver disease."},
    {"term": "Thyroid stimulating hormone (TSH)", "definition": "A hormone produced by the pituitary gland that stimulates the thyroid to produce T4 and T3. TSH testing is the best screening test for thyroid function."},
    {"term": "Transferrin", "definition": "A protein produced by the liver that transports about one-third of the body''s iron."},
    {"term": "Trigeminy", "definition": "A rhythm where every third beat is a premature ventricular contraction (PVC)."},
    {"term": "Troponin I and T", "definition": "A type of protein found in cardiac and skeletal muscle. Levels are evaluated to detect acute coronary syndrome."},
    {"term": "Unstable angina", "definition": "A change in the pattern of stable angina characterized by an increase in pain, not responding to a single nitroglycerin or rest, and persisting for greater than 5 minutes."},
    {"term": "Urinalysis", "definition": "An analysis of urine components and their normal findings, including color, clarity, specific gravity, pH, and presence of sediment, glucose, ketones, or proteins."},
    {"term": "Venous refill time", "definition": "An assessment of perfusion where the patient lies supine and the leg is elevated, with time measured for the veins to bulge again upon dependency. Normal is 5-15 seconds."},
    {"term": "Ventilation/perfusion ratio (V/Q ratio)", "definition": "The ratio used to maintain homeostasis; a normal ratio is 0.8. Deviations indicate a mismatch that can be caused by pulmonary or cardiac problems."},
    {"term": "Ventricular asystole", "definition": "A condition often referred to as \"cardiac arrest\" with absence of audible heartbeat, palpable pulse, and respirations."},
    {"term": "Ventricular fibrillation (VF)", "definition": "A rapid, very irregular ventricular rate >300 beats per minute with no atrial activity observable on the ECG. It is a life-threatening condition requiring immediate defibrillation."},
    {"term": "Ventricular tachycardia (VT)", "definition": "A rhythm with greater than 3 PVCs in a row with a ventricular rate of 100-200 beats per minute."},
    {"term": "Virchow''s triad", "definition": "A set of three common risk factors for acute venous thromboembolism: hemodynamic changes (stasis), hypercoagulability, and endothelial injury/dysfunction."},
    {"term": "WBC count and differential", "definition": "A measure of the total number of white blood cells (leukocytes) and the percentage of each different type of leukocyte. An increase in immature neutrophils is known as a \"shift to the left\"."}
  ]'::jsonb
)
ON CONFLICT DO NOTHING;

-- Insert Episode 10: Medical-Surgical
INSERT INTO study_guides (episode_id, title, short_answer_questions, essay_questions, glossary)
VALUES (
  10,
  'Medical-Surgical Study Guide',
  '[
    {"question": "What are the primary differences between cardioversion and emergency defibrillation?", "answer": "Cardioversion is a synchronized electrical stimulation sent to the heart to convert tachyarrhythmias, and it is typically performed as an elective procedure after at least 3 weeks of anticoagulation. In contrast, emergency defibrillation is a non-synchronized shock delivered to treat life-threatening conditions like ventricular fibrillation or pulseless ventricular tachycardia."},
    {"question": "Describe the pathophysiology of Acute Respiratory Distress Syndrome (ARDS).", "answer": "ARDS is a severe inflammatory condition where lung capillaries leak fluid, which accumulates between and within the alveoli. This process, driven by a release of cytokines, impairs gas exchange, leading to refractory hypoxemia and decreased lung compliance, and it carries a mortality rate of 25-50%."},
    {"question": "What are the four types of ventilator-induced lung injury (VILI)?", "answer": "The four interrelated determinants of VILI are barotrauma (damage from excessive pressure), volutrauma (damage from high tidal volume), atelectrauma (damage from repetitive opening and closing of alveoli), and biotrauma (an inflammatory response in the lung)."},
    {"question": "Differentiate between the two primary types of ischemic strokes.", "answer": "The two main types are thrombotic and embolic. A thrombotic stroke occurs when arteriosclerosis blocks a large vessel supplying the brain, often preceded by transient ischemic attacks. An embolic stroke happens when a clot travels from elsewhere in the body, such as from cardiac arrhythmia, and lodges in a brain artery."},
    {"question": "What are the key distinctions between Type 1 and Type 2 Diabetes Mellitus?", "answer": "Type 1 Diabetes is an immune-mediated condition characterized by insufficient insulin production due to beta cell destruction, often presenting with abrupt symptoms like polyuria, polydipsia, and weight loss. Type 2 Diabetes is defined by insulin resistance, tends to develop in older adults, and may present with mild or absent symptoms."},
    {"question": "List three common causes of agitation in a critically ill patient and the primary treatment approach.", "answer": "Common factors contributing to agitation include sleep deprivation, hypoxemia, electrolyte imbalances, pain, and adverse drug reactions. The primary treatment approach is to identify and correct the underlying cause, use verbal de-escalation, and promote normal sleep patterns."},
    {"question": "Describe the purpose and common uses of pacemakers.", "answer": "Pacemakers are used to electrically stimulate the heart when its natural conduction system is defective, treating conditions like symptomatic bradycardia or high-degree AV block. They can also be used to \"overdrive\" tachyarrhythmias, provide cardiac support post-surgery, or diagnose dysrhythmias through electrophysiology studies."},
    {"question": "What is Status Epilepticus and why is it a medical emergency?", "answer": "Status Epilepticus is a series of generalized tonic-clonic seizures without any intervening periods of consciousness. It is considered a medical emergency because the unrelenting seizure activity can lead to severe complications such as exhaustion, respiratory failure with hypoxemia, hypercapnia, cardiac failure, and death."},
    {"question": "What are the main causes and symptoms of an acute pulmonary embolism (PE)?", "answer": "The most common cause of a PE is a thrombus from the deep veins of the legs, but air, fat, or septic emboli can also be responsible. Key symptoms vary with the size of the embolus but often include dyspnea, tachypnea, cyanosis, chest pain, tachycardia, and fever, potentially progressing to hemodynamic instability."},
    {"question": "Explain the pathophysiology of Diabetic Ketoacidosis (DKA).", "answer": "DKA is a severe complication of Type 1 diabetes where a lack of insulin means glucose cannot be used for energy. The body breaks down fat instead, producing ketone bodies that accumulate in the blood and urine, causing metabolic acidosis, dehydration, and potentially life-threatening electrolyte imbalances."}
  ]'::jsonb,
  '[
    {"question": "Compare and contrast the pathophysiology, clinical presentation, and management of chronic bronchitis and emphysema, including their relationship to Chronic Obstructive Pulmonary Disease (COPD).", "guidance": "Formulate detailed responses to the following essay prompts based on the provided source context."},
    {"question": "Describe the step-by-step procedure for rapid sequence intubation (RSI) as outlined in the text, and explain the methods used to confirm correct placement of an endotracheal tube.", "guidance": "Formulate detailed responses to the following essay prompts based on the provided source context."},
    {"question": "Discuss the different types of dementia mentioned (Creutzfeldt-Jakob, Dementia with Lewy Bodies, Frontotemporal, Normal pressure hydrocephalus, Parkinson''s, Vascular). For three of these types, detail their unique characteristics and symptoms.", "guidance": "Formulate detailed responses to the following essay prompts based on the provided source context."},
    {"question": "Explain the progression of Guillain-Barré Syndrome (GBS) from initial symptoms to potential complications. Outline the primary treatment strategies and their goals.", "guidance": "Formulate detailed responses to the following essay prompts based on the provided source context."},
    {"question": "Analyze the causes, diagnosis, and management of acute respiratory failure, differentiating between hypoxemic and hypercapnic failure.", "guidance": "Formulate detailed responses to the following essay prompts based on the provided source context."}
  ]'::jsonb,
  '[
    {"term": "Acute Lung Injury (ALI)", "definition": "A syndrome of acute and persistent lung inflammation with increased vascular permeability, a precursor to ARDS."},
    {"term": "Acute Respiratory Distress Syndrome (ARDS)", "definition": "A severe inflammatory condition culminating in refractory hypoxemia and respiratory failure, with a mortality rate of 25-50%."},
    {"term": "Acute Respiratory Failure", "definition": "A condition where the lungs cannot adequately perform gas exchange. It includes hypoxemic failure (oxygenation failure) and hypercapnic failure (ventilation failure)."},
    {"term": "Agitation", "definition": "A common occurrence in critically ill patients with numerous contributing factors, including drug withdrawal, sleep deprivation, hypoxemia, and pain."},
    {"term": "Amyotrophic Lateral Sclerosis (ALS)", "definition": "A progressive degenerative disease of the upper and lower motor neurons, resulting in progressive muscle weakness and paralysis."},
    {"term": "Arterial Line", "definition": "An indwelling catheter in an artery for hemodynamic monitoring, frequent ABG monitoring, or placement of an IABP."},
    {"term": "Aspiration Pneumonitis/Pneumonia", "definition": "Lung inflammation that occurs as the result of any type of aspiration, leading to an inflammatory response."},
    {"term": "Astrocytoma", "definition": "A type of brain tumor arising from astrocytes. It is the most common type of tumor occurring throughout the brain."},
    {"term": "Automatic Implantable Cardioverter-Defibrillator (AICD)", "definition": "A device similar to a pacemaker that is used to control tachyarrhythmias such as ventricular tachycardia or fibrillation."},
    {"term": "Brain Death", "definition": "The irreversible cessation of circulatory and respiratory function or the irreversible cessation of all functions of the entire brain, including the brain stem."},
    {"term": "Cardioversion", "definition": "A timed electrical stimulation to the heart to convert tachyarrhythmias, such as atrial fibrillation or ventricular tachycardia."},
    {"term": "Cerebral Palsy (CP)", "definition": "A non-progressive motor dysfunction related to CNS damage associated with congenital, hypoxic, or traumatic injury before, during, or <5 years after birth."},
    {"term": "Chronic Asthma", "definition": "A condition where airway obstruction is not constant and is largely reversible. It affects the bronchi and bronchioles with inflammation resulting in airway obstruction."},
    {"term": "Chronic Bronchitis", "definition": "A pulmonary airway disease characterized by severe cough with sputum production for at least 3 months for two consecutive years."},
    {"term": "Chronic Obstructive Pulmonary Disease (COPD)", "definition": "A chronic disease state assessed using forced expiratory volume (FEV1), forced vital capacity (FVC), body mass index (BMI), and spirometry."},
    {"term": "Delirium", "definition": "An acute, sudden, and fluctuating change in consciousness. It occurs in 10-40% of hospitalized patients."},
    {"term": "Dementia", "definition": "A chronic condition in which there is progressive and irreversible loss of memory and function."},
    {"term": "Diabetes Mellitus", "definition": "The most common metabolic disorder. Over 4% of adults have diabetes."},
    {"term": "Diabetic Ketoacidosis (DKA)", "definition": "A complication of type 1 diabetes, usually related to noncompliance with insulin therapy."},
    {"term": "Emergency Defibrillation", "definition": "A non-synchronized electrical shock given to treat acute ventricular fibrillation, pulseless ventricular tachycardia, or polymorphic ventricular tachycardia with a rapid rate and poor perfusion."},
    {"term": "Emphysema", "definition": "A component of COPD characterized by abnormal distention of air spaces at the terminal bronchioles, with destruction of alveolar walls."},
    {"term": "Endotracheal Intubation", "definition": "A procedure often necessary with respiratory failure for control of hypoxemia, hypercapnia, hypoventilation, and/or for obstructed airway."},
    {"term": "Epilepsy", "definition": "A condition diagnosed based on a history of seizure activity as well as supporting EEG findings."},
    {"term": "Guillain-Barré Syndrome (GBS)", "definition": "An autoimmune disorder of the myelinated motor peripheral nervous system, causing ascending and descending paralysis."},
    {"term": "Multiple Sclerosis (MS)", "definition": "An autoimmune disorder of the CNS in which the myelin sheath around the nerves is damaged and replaced by scar tissue that prevents conduction of nerve impulses."},
    {"term": "Myasthenia Gravis", "definition": "An autoimmune disorder that results in sporadic, progressive weakness of striated muscle."},
    {"term": "Non-Invasive Positive Pressure Ventilation (NIPPV)", "definition": "Ventilation given through a tight-fitting nasal or face mask, usually pressure cycled, avoiding the need for intubation."},
    {"term": "Pacemaker", "definition": "A device used to stimulate the heart when the normal conduction system of the heart is defective."},
    {"term": "Pacemaker Syndrome", "definition": "A condition that can occur with any type of pacemaker if there is inadequate synchronicity between the atria and the ventricles."},
    {"term": "Parkinson''s Disease", "definition": "An extrapyramidal movement/motor system disorder caused by loss of brain cells that produce dopamine."},
    {"term": "Pericardiocentesis", "definition": "A procedure that uses ultrasound guidance to diagnose pericardial effusion or with ECG and ultrasound guidance to relieve cardiac tamponade."},
    {"term": "Pneumonia", "definition": "An inflammatory process of the lung parenchyma, filling the alveoli with exudate."},
    {"term": "Pulmonary Embolism (Acute)", "definition": "A condition where a pulmonary artery or arteriole is blocked, cutting off blood supply to the pulmonary vessels and subsequent oxygenation of the blood."},
    {"term": "Rapid Sequence Intubation (RSI)", "definition": "The nearly simultaneous giving of a sedative and a paralytic in order to facilitate emergency intubation."},
    {"term": "Seizure Disorders", "definition": "Conditions caused by electrical discharges to a localized area of the cerebral cortex (partial) or involving both hemispheres (generalized)."},
    {"term": "Status Asthmaticus", "definition": "A severe acute attack of asthma that does not respond to conventional therapy."},
    {"term": "Status Epilepticus (SE)", "definition": "Generalized tonic-clonic seizures that are characterized by a series of seizures with no intervening periods of consciousness."},
    {"term": "Stroke", "definition": "A cerebrovascular accident (CVA) resulting from an interruption of the blood flow to an area of the brain."},
    {"term": "Transient Ischemic Attack (TIA)", "definition": "A condition with stroke-like symptoms from small clots that cause similar but short-lived (minutes to hours) symptoms."},
    {"term": "Ventilator-Induced Lung Injury (VILI)", "definition": "Lung damage caused by mechanical ventilation, common in ARDS. It comprises four interrelated determinants: barotrauma, volutrauma, atelectrauma, and biotrauma."}
  ]'::jsonb
)
ON CONFLICT DO NOTHING;
