-- Insert Episode 11: Pathophysiology Review
INSERT INTO study_guides (episode_id, title, short_answer_questions, essay_questions, glossary)
VALUES (
  11,
  'Study Guide: Pathophysiology Review',
  '[
    {"question": "What is biliary atresia, and what is the life expectancy for an infant with this condition if left untreated?", "answer": "Biliary atresia is a life-threatening condition of unknown cause that occurs in infancy. It involves bile ducts that transport bile from the liver failing, leading to trapped bile that damages the liver. The life expectancy for infants with untreated biliary atresia is approximately two years."},
    {"question": "Describe the initial fluid resuscitation protocol for a patient with Diabetic Ketoacidosis (DKA).", "answer": "The priority in treating DKA is fluid resuscitation, which typically involves administering 1-2 liters of isotonic fluids in the first hour. Over the first 24 hours, a patient may receive up to 8 liters of fluid. Potassium is added to the fluids once the level begins to fall."},
    {"question": "What are the hallmark signs and symptoms of a thyrotoxic storm?", "answer": "A thyrotoxic storm is a severe type of hyperthyroidism with sudden onset. Its hallmark symptoms include a significant increase in hyperthyroidism symptoms, tachycardia exceeding 140 bpm with atrial fibrillation and heart failure, gastrointestinal disorders, and an altered mental status that can progress to coma."},
    {"question": "Explain the primary difference between Ulcerative Colitis and Crohn''s disease in terms of the affected areas and depth of inflammation in the GI tract.", "answer": "Ulcerative colitis involves superficial inflammation of the mucosa of the colon and rectum, causing ulcerations that bleed and produce purulent material. In contrast, Crohn''s disease is characterized by transmural inflammation (affecting the entire thickness of the intestinal wall) and can occur discontinuously anywhere in the GI tract."},
    {"question": "What is Disseminated Intravascular Coagulation (DIC), and what two contradictory processes does it trigger?", "answer": "Disseminated Intravascular Coagulation (DIC) is a secondary disorder triggered by major trauma or infection where the coagulation process is overstimulated. It paradoxically triggers both coagulation (forming fibrin clots throughout the intravascular system) and hemorrhage (due to the consumption of platelets and clotting factors)."},
    {"question": "Identify the diagnostic criteria for AIDS as it relates to HIV infection.", "answer": "AIDS is diagnosed in a person with HIV infection when either their CD4 count falls below 200 cells/mm³ or they present with an AIDS-defining condition. Examples of AIDS-defining conditions include opportunistic infections like cytomegalovirus or tuberculosis, or conditions like Kaposi''s sarcoma."},
    {"question": "What is Sickle Cell Disease, and which demographic is most commonly affected in the United States?", "answer": "Sickle Cell Disease is an autosomal recessive genetic disorder affecting chromosome 11, causing hemoglobin to be defective. This results in red blood cells becoming sickle-shaped, leading to blockages in small vessels. It most commonly affects African Americans, with 8-10% being carriers in the United States."},
    {"question": "Describe the Kasai procedure and its purpose in treating biliary atresia.", "answer": "The Kasai procedure is a surgical treatment option for biliary atresia. The procedure involves using a loop of the intestine to create a new bile duct after removing the damaged ducts, allowing bile to drain from the liver directly into the small intestine."},
    {"question": "What are esophageal varices, and why do they pose a significant risk to patients with cirrhosis?", "answer": "Esophageal varices are tortuous, dilated veins in the submucosa of the esophagus, which are a complication of cirrhosis. Because these veins are fragile and inelastic, they tear easily, which can cause sudden, massive, and potentially fatal esophageal hemorrhage."},
    {"question": "List three potential non-infectious complications associated with blood transfusions.", "answer": "Three non-infectious complications of blood transfusions are Transfusion-related acute lung injury (TRALI), Graft vs. host disease, and Hypothermia. Other potential complications include Post-transfusion purpura and Transfusion-related immunosuppression."}
  ]'::jsonb,
  '[
    {"question": "Compare and contrast Hyperosmolar Hyperglycemic Nonketotic Syndrome (HHNS) and Diabetic Ketoacidosis (DKA). Discuss the typical patient profile, key physiological differences related to osmolarity and ketones, and the primary treatment approaches for each.", "guidance": "Formulate detailed responses to the following prompts, integrating relevant pathophysiology, symptoms, and treatment strategies as described in the source materials."},
    {"question": "Explain the pathophysiology of portal hypertension. Detail its causes, the physiological consequences (including the development of ascites and esophageal varices), and the range of treatment options from lifestyle modifications to surgical interventions.", "guidance": "Formulate detailed responses to the following prompts, integrating relevant pathophysiology, symptoms, and treatment strategies as described in the source materials."},
    {"question": "Describe the progression of hepatic disease from compensated cirrhosis to decompensated cirrhosis and finally to hepatic coma (encephalopathy). For each stage, discuss the characteristic symptoms and the underlying physiological failures of the liver.", "guidance": "Formulate detailed responses to the following prompts, integrating relevant pathophysiology, symptoms, and treatment strategies as described in the source materials."},
    {"question": "Discuss the diagnosis and treatment of three distinct bleeding disorders: Von Willebrand Disease, Hemophilia A, and Idiopathic Thrombocytopenic Purpura (ITP). Highlight the differences in their underlying causes (clotting factors vs. platelets) and how these differences dictate their respective treatments.", "guidance": "Formulate detailed responses to the following prompts, integrating relevant pathophysiology, symptoms, and treatment strategies as described in the source materials."},
    {"question": "Detail the pathophysiology, causes, symptoms, and treatment of Thyrotoxic Storm. Explain why this condition is considered a medical emergency and outline the multi-faceted therapeutic approach required to manage it.", "guidance": "Formulate detailed responses to the following prompts, integrating relevant pathophysiology, symptoms, and treatment strategies as described in the source materials."}
  ]'::jsonb,
  '[
    {"term": "AIDS (Acquired Immunodeficiency Syndrome)", "definition": "A progression of HIV infection diagnosed when CD4 count is less than 200 cells/mm³ or when an AIDS-defining condition is present."},
    {"term": "Anemia", "definition": "A condition where there is an insufficient number of red blood cells to adequately oxygenate the body, resulting in decreased oxygen supply to organs."},
    {"term": "Appendicitis", "definition": "Inflammation of the appendix, often caused by luminal obstruction and pressure within the appendix wall that can compromise blood supply."},
    {"term": "Biliary Atresia", "definition": "A rare, life-threatening condition in infancy of unknown cause where bile ducts fail to transport bile from the liver, leading to liver damage."},
    {"term": "Cholecystitis", "definition": "Inflammation of the gallbladder that is usually the result of obstruction of the bile duct related to calculi (gallstones)."},
    {"term": "Cirrhosis", "definition": "A chronic hepatic disease in which normal liver tissue is replaced by fibrotic tissue, impairing liver function. Can be compensated or decompensated."},
    {"term": "Crohn''s Disease", "definition": "A type of inflammatory bowel disease with transmural inflammation that can affect any part of the GI system, often leading to strictures, abscesses, and fistulas."},
    {"term": "Diabetic Ketoacidosis (DKA)", "definition": "A complication of uncontrolled diabetes where a lack of insulin causes hyperglycemia, dehydration, electrolyte imbalances, and metabolic acidosis."},
    {"term": "Disseminated Intravascular Coagulation (DIC)", "definition": "A secondary disorder, often from trauma or sepsis, that triggers both coagulation and hemorrhage throughout the intravascular system simultaneously."},
    {"term": "Esophageal Varices", "definition": "Tortuous, dilated veins in the submucosa of the esophagus, often a complication of portal hypertension, which can rupture and cause massive hemorrhage."},
    {"term": "Gastroenteritis", "definition": "Commonly referred to as a stomach flu, it is an intestinal infection characterized by nausea, vomiting, abdominal cramps, and diarrhea. Can be viral, bacterial, or parasitic."},
    {"term": "Hemophilia", "definition": "An inherited disorder in which the person lacks adequate clotting factors. Type A involves a lack of clotting factor VIII, and Type B involves a lack of factor IX."},
    {"term": "Hepatic Encephalopathy (Hepatic Coma)", "definition": "A decrease in neurologic function that occurs when the liver''s inability to remove ammonia and other toxins from the bloodstream causes a decrease in neurologic function."},
    {"term": "HHNS (Hyperosmolar Hyperglycemic Nonketotic Syndrome)", "definition": "Occurs in people without a history of diabetes or with mild type 2 diabetes, leading to osmotic diuresis, hypernatremia, and increased osmolarity."},
    {"term": "Hyperthyroidism", "definition": "A condition that usually results from excess production of thyroid hormones, leading to symptoms like hyperexcitability, tachycardia, and poor heat tolerance."},
    {"term": "Hypoglycemia", "definition": "An acute condition that may result from pancreatic islet tumors, hyperplasia, or excessive insulin use, causing blood glucose to fall below 50-60 mg/dL."},
    {"term": "Hypothyroidism", "definition": "A condition that occurs when the thyroid produces inadequate levels of thyroid hormones, leading to symptoms such as chronic fatigue, low pulse rate, and weight gain."},
    {"term": "ITP (Idiopathic Thrombocytopenic Purpura)", "definition": "An autoimmune disorder that causes an immune response against platelets, resulting in decreased platelet counts."},
    {"term": "Kasai Procedure", "definition": "A surgical treatment for biliary atresia that involves using a loop of intestine to act as a new bile duct, removing the damaged ducts."},
    {"term": "Lymphedema", "definition": "A chronic condition marked by swelling and fluid retention that results from untreated or incurable edema due to accumulation of protein-rich fluid."},
    {"term": "Neutropenia", "definition": "A sustained condition where the polymorphonuclear neutrophil count is less than 500/mL, making a patient highly susceptible to infection."},
    {"term": "Peritonitis", "definition": "Inflammation of the peritoneum, the membrane lining the abdominal cavity, which may be primary (from infection) or secondary (from rupture of an abdominal organ)."},
    {"term": "Peptic Ulcer Disease (PUD)", "definition": "Includes both ulcerations of the duodenum and stomach, primarily caused by H. pylori infections (80%) or by aspirin and NSAIDs."},
    {"term": "Portal Hypertension", "definition": "A condition where elevated blood flow pressure throughout the portal venous system occurs, often due to obstruction of blood flow from the liver."},
    {"term": "Sickle Cell Disease", "definition": "An autosomal recessive genetic disorder (chromosome 11) causing defective hemoglobin, which results in red blood cells becoming sickle-shaped and inflexible."},
    {"term": "Thrombocytopenia", "definition": "A deficiency of circulating platelets in the blood, defined as a platelet count of less than 150,000/mm³."},
    {"term": "Thyrotoxic Storm", "definition": "A severe type of hyperthyroidism with sudden onset, precipitated by stress, surgery, or injury, and considered a medical emergency."},
    {"term": "TRALI (Transfusion-related acute lung injury)", "definition": "A serious transfusion complication that occurs as a result of antileukocytic or anti-HLA antibodies in the transfusion, characterized by non-cardiogenic pulmonary edema."},
    {"term": "Ulcerative Colitis", "definition": "A type of inflammatory bowel disease characterized by superficial inflammation of the colon and rectum, causing ulcerations that bleed and produce purulent material."},
    {"term": "Von Willebrand Disease", "definition": "A congenital bleeding disorder affecting 1-2% of the population, caused by a deficiency or lack of von Willebrand factor (vWF), a glycoprotein essential for clotting."}
  ]'::jsonb
)
ON CONFLICT DO NOTHING;

-- Insert Episode 12: Medical Procedures and Pathophysiology
INSERT INTO study_guides (episode_id, title, short_answer_questions, essay_questions, glossary)
VALUES (
  12,
  'Medical Procedures and Pathophysiology Study Guide',
  '[
    {"question": "Describe the primary differences between Levin tubes and Sump tubes regarding their structure and suction capabilities.", "answer": "Levin tubes are single-lumen tubes that lack a vent, restricting them to use with low suction only for draining gastric secretions. Sump tubes, in contrast, are plastic or vinyl tubes that possess a vent lumen, which prevents a vacuum from forming and allows them to be used safely with high suction."},
    {"question": "What is the primary purpose of a tourniquet, and what is the first priority in managing a wound where one might be considered?", "answer": "Tourniquets are used to control arterial hemorrhage in an extremity. The first priority, however, is always to prevent exsanguination, and tourniquets should only be applied immediately when this type of severe bleeding is present."},
    {"question": "Explain the fundamental distinction between enteral and parenteral nutrition.", "answer": "Enteral nutrition involves providing nutrition through a tube placed into the gastrointestinal tract (e.g., nose, stomach, or jejunum), where nutrients are absorbed by the patient''s digestive system. Parenteral nutrition (TPN) bypasses the digestive system entirely by administering nutrients through an intravenous line, a method preferred for patients with compromised GI tracts."},
    {"question": "Define Compartment Syndrome and outline its definitive treatment.", "answer": "Compartment syndrome occurs when there is an increase in the amount of pressure within a group of muscles, which compresses nerves and blood vessels, often after a fracture. The definitive treatment is a surgical fasciotomy, which involves opening the skin and muscle fascia to relieve the pressure and prevent tissue death."},
    {"question": "What is Acute Kidney Injury (AKI), and what are some of its common risk factors?", "answer": "Acute Kidney Injury (AKI), formerly known as acute renal failure, is a sudden disruption of kidney function leading to decreased renal perfusion, a drop in glomerular filtration rate, and a buildup of uremic waste products. Common risk factors include advanced age, the presence of diabetes, and pre-existing kidney or heart disease."},
    {"question": "Describe the difference between a sprain and a strain, including the tissues involved.", "answer": "A strain is an overstretching of a muscle or the musculotendinous unit, often called a \"pulled muscle,\" which causes microscopic tears. A sprain is an injury to a joint caused by a partial rupture of its supporting ligaments, usually due to stretching beyond their normal capacity."},
    {"question": "What is Pelvic Inflammatory Disease (PID), and which two organisms are implicated in most cases?", "answer": "Pelvic Inflammatory Disease (PID) is a serious infection of the upper reproductive system that can result in infertility and ectopic pregnancy. The organisms most commonly implicated in PID cases are Neisseria gonorrhoeae and Chlamydia trachomatis."},
    {"question": "List three key strategies for reducing the risk of infection associated with urinary catheters.", "answer": "Strategies for reducing urinary catheter infection risks include using aseptic technique for insertion, limiting catheter use by establishing protocols for duration and removal, utilizing closed-drainage systems, and maintaining proper urinary flow by securing the catheter and tubing."},
    {"question": "Define rhabdomyolysis and identify its most serious complication.", "answer": "Rhabdomyolysis occurs when the death of skeletal muscle cells causes the release of toxins into the bloodstream, which can cause kidney damage. The most serious complication is renal failure, and treatment is critical to avoid this and other serious issues."},
    {"question": "How should an amputated part be cared for to maximize the chances of successful reattachment?", "answer": "An amputated part should be cooled to 4°C to extend its viability by rinsing it with normal saline (NS), wrapping it in saline-moistened gauze, and placing it in a sealed plastic bag. This bag should then be placed in ice water (1:1 ice to water), ensuring the part is not immersed directly in saline and avoiding freezing the part."}
  ]'::jsonb,
  '[
    {"question": "Compare and contrast the pathophysiology, common causes, symptoms, and treatment approaches for Acute Kidney Injury (AKI) and Chronic Kidney Disease (CKD).", "guidance": "Formulate comprehensive essay-style answers to the following prompts, synthesizing information from across the provided source material."},
    {"question": "Discuss the potential systemic complications of severe traumatic injuries, focusing on Fat Embolism, Compartment Syndrome, and Rhabdomyolysis. For each condition, describe the mechanism of injury, key signs and symptoms, and primary treatments.", "guidance": "Formulate comprehensive essay-style answers to the following prompts, synthesizing information from across the provided source material."},
    {"question": "Outline the various types of medical drains discussed in the text (Simple, Penrose, Sump, Jackson-Pratt, Hemovac). Explain their individual mechanisms of action, typical applications, and relevant nursing considerations.", "guidance": "Formulate comprehensive essay-style answers to the following prompts, synthesizing information from across the provided source material."},
    {"question": "Describe the process and potential complications of providing enteral nutrition via feeding tubes. Detail troubleshooting methods for common issues such as vomiting/aspiration, diarrhea, and tube displacement.", "guidance": "Formulate comprehensive essay-style answers to the following prompts, synthesizing information from across the provided source material."},
    {"question": "Analyze the principles and methods of musculoskeletal immobilization for trauma patients. Discuss the indications for different devices (e.g., cervical collars, splints, PASG) and explain the NEXUS criteria for determining the necessity of spinal immobilization.", "guidance": "Formulate comprehensive essay-style answers to the following prompts, synthesizing information from across the provided source material."}
  ]'::jsonb,
  '[
    {"term": "Acute Kidney Injury (AKI)", "definition": "An acute disruption of kidney function that results in decreased renal perfusion, a decrease in glomerular filtration rate, and a buildup of uremic waste products (azotemia)."},
    {"term": "Acute Tubular Necrosis (ATN)", "definition": "A hypoxic condition causing renal ischemia that damages tubular cells of the nephron, leading to acute renal failure. Can result from nephrotoxic injury related to obstruction or drugs."},
    {"term": "Allen Test", "definition": "A test done to determine arterial injury if digits are amputated. The ulnar artery is compressed, the patient clenches and releases the hand until it blanches, the pressure is released, and the time for the hand to flush is noted."},
    {"term": "Bartholin Cysts", "definition": "A blockage of one of the Bartholin glands, located on both sides of the vagina, usually caused by infection or trauma, resulting in swelling and cyst formation."},
    {"term": "Benign Prostatic Hypertrophy (BPH)", "definition": "A common condition in men over 40 where the prostate gland enlarges, compressing the urethra and causing frequent urination, urgency, dribbling, and nocturia."},
    {"term": "Closed Drainage Systems", "definition": "Systems that use low-pressure suction to provide continuous gravity drainage of wounds. Examples include Jackson-Pratt and Hemovac drains."},
    {"term": "Compartment Syndrome", "definition": "A condition where increased pressure within a group of muscles compromises blood flow to muscles and nerves. It often occurs after a fracture and is a surgical emergency."},
    {"term": "Cystitis", "definition": "A common, often low-grade kidney infection that develops over time."},
    {"term": "Dialysis", "definition": "A procedure for those who have progressed from renal insufficiency to uremia with end-stage renal disease (ESRD). It may be temporary for acute conditions."},
    {"term": "Enteral Nutrition", "definition": "A method of providing nutrition to a patient through a tube placed in the GI tract (nose, stomach, or jejunum), where nutrients are absorbed by the digestive system."},
    {"term": "Epididymitis", "definition": "Infection of the epididymis, often associated with infection in a testis (epididymo-orchitis)."},
    {"term": "Fat Embolism", "definition": "A complication of traumatic fracture where fat emboli from bone marrow enter the bloodstream and travel to the lungs, potentially causing pulmonary failure."},
    {"term": "Hemodialysis", "definition": "A common type of dialysis where blood is circulated outside of the body through a dialyzer. It can be used for short-term or long-term treatment."},
    {"term": "Hemovac", "definition": "A round drain with coiled springs inside that are compressed after emptying to create suction, capable of holding up to 500 mL of drainage."},
    {"term": "Hydronephrosis", "definition": "A disease involving swelling of the kidney pelvives and calyces because of an obstruction of normal urine flow from the kidney."},
    {"term": "Jackson-Pratt", "definition": "A bulb-type drain about the size of a lemon that can hold about 100 mL of drainage. It extends a thin plastic drain from the wound and is squeezed to create suction."},
    {"term": "Levin Tube", "definition": "A single-lumen NG tube with no vent, used only with low suction to drain gastric secretions."},
    {"term": "Nasogastric (NG) Tubes", "definition": "Plastic or vinyl tubes inserted through the nose, down the esophagus, and into the stomach for gastrointestinal procedures."},
    {"term": "Nephrotoxic Agents", "definition": "Medications that are a common cause of renal damage, especially among older patients."},
    {"term": "Ovarian Cysts", "definition": "Cysts that can grow on or in the ovaries, which can be functional (follicular, corpus luteum) or other types (cystadenomas, endometriomas, teratomas)."},
    {"term": "Paraphimosis", "definition": "Occurs when the foreskin is retracted above the glans penis and cannot be returned to its normal position, causing edema and potential gangrene. It is a critical medical emergency."},
    {"term": "Parenteral Nutrition", "definition": "Also known as Total Parenteral Nutrition (TPN), it is a method of providing nutrition that completely bypasses the digestive system by administering nutrients through an intravenous line."},
    {"term": "PEG Tube", "definition": "Percutaneous endoscopic gastrostomy (PEG) tube used for tube feedings, involving the intubation of the esophagus with an endoscope and insertion of a sheathed needle into the abdomen and stomach."},
    {"term": "Pelvic Inflammatory Disease (PID)", "definition": "A serious infection of the upper reproductive system, often ascending from the vagina and cervix, which can cause chronic pelvic pain, infertility, and ectopic pregnancy."},
    {"term": "Penrose Drains", "definition": "Flat, soft rubber/latex tubes placed in surgical wounds to drain fluid by gravity and capillary action."},
    {"term": "Peritoneal Dialysis", "definition": "A type of dialysis where an indwelling catheter is surgically inserted into the peritoneal cavity, and dialysate solution is slowly instilled and drained in a series of exchanges."},
    {"term": "Phimosis", "definition": "A structural problem with restrictive disorders of the penis that occurs in uncircumcised or incorrectly circumcised males, where there is an inability to retract the foreskin."},
    {"term": "Prostatitis", "definition": "An acute infection of the prostate gland, commonly caused by Escherichia coli."},
    {"term": "Pyelonephritis", "definition": "A potentially organ-damaging bacterial infection of the parenchyma of the kidney."},
    {"term": "Rhabdomyolysis", "definition": "Occurs when the death of the cells of the skeletal muscles causes the release of toxins from those cells into the bloodstream, which can cause kidney damage."},
    {"term": "Sprain", "definition": "Damage to a joint with a partial rupture of the supporting ligaments, usually caused by stretching the joint beyond its normal capacity."},
    {"term": "Strain", "definition": "An overstretching of a part of the musculature (\"pulled muscle\") that causes microscopic tears in the muscle."},
    {"term": "Sump Drains", "definition": "Double-lumen or tri-lumen tubes used for infusions, producing venting when air enters the inflow lumen and forces drainage out of the large lumen."},
    {"term": "Sump Tubes", "definition": "Plastic or vinyl NG tubes that include a vent lumen to prevent a vacuum from forming with high suction."},
    {"term": "Testicular Torsion", "definition": "Twisting of the spermatic cord within or below the inguinal canal, causing constriction of blood supply to the testis. This is a surgical emergency."},
    {"term": "Tourniquet", "definition": "A device used to control hemorrhage in an extremity, applied immediately with arterial bleeding."},
    {"term": "Uremic Syndrome", "definition": "A number of disorders that occur with end-stage renal disease and renal failure, usually after multiple metabolic failures and a decrease in creatinine clearance to <10 mL/min."},
    {"term": "Urinary Incontinence", "definition": "Involuntary leakage of urine, more common in women. Types include stress, urge, overflow, functional, and total incontinence."},
    {"term": "Vulvovaginitis", "definition": "Inflammation of the vulvar and vaginal tissues."}
  ]'::jsonb
)
ON CONFLICT DO NOTHING;
